const test=require('node:test');const assert=require('node:assert/strict');const{readFile}=require('node:fs/promises');const path=require('node:path');
process.env.PUBLIC_RENEWAL_TOKEN_SECRET='test-secret-that-is-at-least-thirty-two-bytes-long';
const{issueRenewalToken,verifyRenewalToken,TOKEN_TTL_SECONDS}=require('../api/public/_renewal-token');
test('signed renewal token is short lived and guessed ID is rejected',()=>{const token=issueRenewalToken({kioskId:42,now:1000000});assert.equal(verifyRenewalToken(token,{now:1000001}).kid,42);assert.equal(TOKEN_TTL_SECONDS,600);assert.throws(()=>verifyRenewalToken('42'),/không hợp lệ/)});
test('expired renewal token is rejected',()=>{const token=issueRenewalToken({kioskId:42,now:1000000});assert.throws(()=>verifyRenewalToken(token,{now:1601000}),error=>error.code==='TOKEN_EXPIRED')});
test('token for Kiosk A cannot authorize Kiosk B',()=>{const token=issueRenewalToken({kioskId:42});assert.throws(()=>verifyRenewalToken(token,{expectedKioskId:43}),error=>error.code==='TOKEN_SCOPE_MISMATCH')});
test('client price is ignored and current server price is authoritative',async()=>{const source=await readFile(path.join(__dirname,'../api/public/renew-kiosk.js'),'utf8');assert.doesNotMatch(source,/parsed\.value\.(amount|price|total)/);assert.match(source,/prepare_public_kiosk_renewal/);assert.match(source,/payment\?\.total_amount/)});
test('renewal authorization is consumed once before payment preparation',async()=>{const migration=await readFile(path.join(__dirname,'../supabase/migrations/20260811120000_secure_public_kiosk_renewal.sql'),'utf8');assert.match(migration,/consumed_at is null/);assert.match(migration,/set consumed_at=now\(\)/);assert.match(migration,/Quyền gia hạn đã hết hạn hoặc đã được sử dụng/)});
test('only signed webhook can complete and retries are idempotent',async()=>{const endpoint=await readFile(path.join(__dirname,'../api/public/renew-kiosk.js'),'utf8');const webhook=await readFile(path.join(__dirname,'../api/payos/webhook.js'),'utf8');const migration=await readFile(path.join(__dirname,'../supabase/migrations/20260731100000_create_payos_order_foundation.sql'),'utf8');assert.doesNotMatch(endpoint,/handle_payos_webhook|payment_status.*completed/);assert.match(webhook,/safeCompareHex\(expectedSignature, signature\)/);assert.match(migration,/if order_record\.status = 'paid'/);assert.match(migration,/already_processed/);assert.match(migration,/for update/)});
