export const PAGE_TITLES = {
  dashboard: 'Tổng quan',
  customers: 'Khách hàng',
  'customer-detail': 'Chi tiết khách hàng',
  kiosks: 'Kiosk',
  'legacy-registration': 'Bổ sung dữ liệu cũ',
  'kiosk-detail': 'Chi tiết Kiosk',
  payments: 'Thanh toán',
  'payments-mine': 'Thanh toán của tôi',
  expenses: 'Chi phí',
  categories: 'Danh mục',
  'business-types': 'Loại hình KD',
  promotions: 'Mã giảm giá',
  logs: 'Lịch sử thay đổi',
  settings: 'Cài đặt',
  'homepage-content': 'Website công khai',
  register: 'Đăng ký trực tuyến',
  'registration-requests': 'Hồ sơ Kiosk',
  staff: 'Quản lý nhân viên',
  'user-management': 'Quản lý người dùng',
  reports: 'Báo cáo',
  permissions: 'Phân quyền',
  user: 'Trang chủ',
  'user-profile': 'Hồ sơ của tôi',
  'user-announcements': 'Thông báo',
  'user-support': 'Hỗ trợ',
  'user-kiosks': 'Kiosk của tôi',
  'user-register-kiosk': 'Đăng ký Kiosk mới',
  'user-facebook': 'Tài khoản Facebook',
};

export const NAV_SECTIONS = [
  {
    label: 'KHU VỰC CÁ NHÂN',
    standalone: true,
    items: [
      { route: 'user', label: 'Trang của tôi', icon: 'user' },
      { route: 'user-profile', label: 'Hồ sơ', icon: 'user-circle' },
      { route: 'user-kiosks', label: 'Kiosk của tôi', icon: 'store' },
      { route: 'user-register-kiosk', label: 'Đăng ký Kiosk', icon: 'plus' },
      { route: 'payments-mine', label: 'Thanh toán của tôi', icon: 'wallet' },
      { route: 'user-announcements', label: 'Thông báo', icon: 'alert' },
      { route: 'user-support', label: 'Hỗ trợ', icon: 'support' },
    ],
  },
  {
    label: 'TỔNG QUAN',
    standalone: true,
    items: [
      { route: 'dashboard', label: 'Dashboard', icon: 'dashboard' },
    ],
  },
  {
    label: 'QUẢN LÝ CRM',
    items: [
      { route: 'customers', label: 'Khách hàng', icon: 'users' },
      { route: 'kiosks', label: 'Kiosk', icon: 'store' },
      { route: 'register', label: 'Đăng ký Kiosk', icon: 'plus' },
      { route: 'registration-requests', label: 'Hồ sơ Kiosk', icon: 'check' },
      { route: 'categories', label: 'Danh mục', icon: 'list' },
      { route: 'business-types', label: 'Loại hình kinh doanh', icon: 'briefcase' },
      { route: 'promotions', label: 'Mã giảm giá', icon: 'coin' },
      { route: 'expenses', label: 'Chi phí', icon: 'receipt' },
      { route: 'reports', label: 'Báo cáo', icon: 'report' },
    ],
  },
  {
    label: 'HỆ THỐNG',
    collapsible: true,
    items: [
      { route: 'user-management', label: 'Quản lý người dùng', icon: 'users' },
      { route: 'logs', label: 'Nhật ký hoạt động', icon: 'history' },
      { route: 'settings', label: 'Cài đặt', icon: 'settings' },
    ],
  },
];
