import { PublicLookupService } from '../services/PublicLookupService.js';
import { isValidPhone } from '../utils/formValidation.js';
import { formatCurrency } from '../utils/currency.js';
import { escapeHtml } from '../utils/html.js';
import { PublicContactLinks, PublicSupport } from '../components/PublicSupport.js';
import { bindPayosCopyButtons, renderPayosQr } from '../components/PayosResultCard.js';

let lookupRows=[];
const renewalTimers=new Map();
export function LookupPage(){return `<section class="portal-page narrow public-lookup-page"><div class="portal-page-heading"><span>Tra cứu công khai</span><h1>Tra cứu Kiosk</h1><p>Nhập số điện thoại đã dùng khi đăng ký để xem thông tin Kiosk an toàn.</p></div><div class="lookup-guide"><strong>Cách sử dụng</strong><span>Nhập số điện thoại → bấm Tra cứu → xem kết quả bên dưới.</span></div><form id="lookup-form" class="lookup-form" novalidate><label class="form-group"><span>Số điện thoại đã đăng ký</span><input id="lookup-phone" class="form-control" type="tel" inputmode="tel" autocomplete="tel" placeholder="Ví dụ: 0888690346" required></label><button class="btn-primary" type="submit">Tra cứu</button></form><div id="lookup-message" class="form-error hidden" role="alert"></div><div id="lookup-results" class="lookup-results" aria-live="polite"></div>${PublicSupport()}</section>`}
LookupPage.afterRender=function(){[...renewalTimers.keys()].forEach(stopRenewalTimers);lookupRows=[];document.getElementById('lookup-form')?.addEventListener('submit',lookup);document.getElementById('lookup-results')?.addEventListener('click',handleResultClick)};
async function lookup(event){event.preventDefault();const phone=document.getElementById('lookup-phone');const message=document.getElementById('lookup-message');const results=document.getElementById('lookup-results');const button=event.currentTarget.querySelector('button');message.classList.add('hidden');results.innerHTML='';if(!isValidPhone(phone.value)){show(message,'Số điện thoại phải có từ 9 đến 15 chữ số.');phone.focus();return}button.disabled=true;button.textContent='Đang tra cứu...';try{const {data=[]}=await PublicLookupService.byPhone(phone.value);lookupRows=data;results.innerHTML=data.length?data.map(resultCard).join(''):'<div class="lookup-empty"><strong>Chưa tìm thấy Kiosk</strong><span>Kiểm tra lại số điện thoại hoặc liên hệ hỗ trợ.</span></div>'}catch(error){show(message,error?.message||'Không thể tra cứu lúc này.')}finally{button.disabled=false;button.textContent='Tra cứu'}}
function resultCard(item,index){const days=remainingDays(item.endDate);return `<article class="lookup-card"><div><span>Kiosk</span><h2>${escapeHtml(item.kiosk||'Kiosk')}</h2></div><dl><div><dt>Danh mục</dt><dd>${escapeHtml(item.category||'—')}</dd></div><div><dt>Loại hình</dt><dd>${escapeHtml(item.businessType||'—')}</dd></div><div><dt>Ngày bắt đầu</dt><dd>${date(item.startDate)}</dd></div><div><dt>Ngày hết hạn</dt><dd>${date(item.endDate)}</dd></div><div><dt>Thời hạn còn lại</dt><dd>${days>=0?`${days} ngày`:'Đã hết hạn'}</dd></div><div><dt>Trạng thái</dt><dd><span class="status-pill">${status(item.status,days)}</span></dd></div></dl><button class="btn-primary lookup-renew-button" type="button" data-renew-index="${index}">Gia hạn Kiosk</button><div data-renew-panel="${index}"></div></article>`}
function handleResultClick(event){const renew=event.target.closest('[data-renew-index]');if(renew)return openRenewal(Number(renew.dataset.renewIndex));const create=event.target.closest('[data-create-public-renewal]');if(create)return createRenewal(Number(create.dataset.createPublicRenewal));const refresh=event.target.closest('[data-refresh-renewal]');if(refresh)return refreshStatus(Number(refresh.dataset.refreshRenewal));const recreate=event.target.closest('[data-new-public-renewal]');if(recreate)return recreateRenewal(Number(recreate.dataset.newPublicRenewal));if(event.target.closest('[data-lookup-again]')){document.getElementById('lookup-results').innerHTML='';document.getElementById('lookup-phone')?.focus();}}
function openRenewal(index){const item=lookupRows[index];const panel=document.querySelector(`[data-renew-panel="${index}"]`);if(!item||!panel)return;if(!item.renewalAvailable){panel.innerHTML=blockedRenewalPanel(item.renewalBlockedReason);return}panel.innerHTML=renewalConfirmationCard(item,index,1);panel.querySelectorAll('[name="public-renew-months"]').forEach(input=>input.addEventListener('change',()=>updateRenewalConfirmation(item,panel,Number(input.value))));}
function blockedRenewalPanel(reason){return `<div class="public-renew-panel public-renew-blocked" role="status"><h3>Chưa thể gia hạn tự động</h3><p>${escapeHtml(renewalBlockedMessage(reason))}</p>${PublicContactLinks({compact:true})}</div>`}
export function renewalBlockedMessage(reason){if(reason==='PENDING_APPROVAL')return'Kiosk đang chờ duyệt nên chưa thể gia hạn. Vui lòng liên hệ Admin để được hỗ trợ.';if(reason==='INVALID_PRICE')return'Hiện chưa xác định được giá gia hạn cho Kiosk này. Vui lòng liên hệ Admin để được hỗ trợ.';return'Tính năng gia hạn tự động hiện chưa sẵn sàng. Vui lòng liên hệ Admin để được hỗ trợ.'}
async function createRenewal(index, monthsOverride){const item=lookupRows[index];const panel=document.querySelector(`[data-renew-panel="${index}"]`);const button=panel?.querySelector('[data-create-public-renewal]');const months=Number(monthsOverride||panel?.querySelector('[name="public-renew-months"]:checked')?.value);if(!item||!panel||!ALLOWED_PUBLIC_MONTHS.has(months))return;if(button){button.disabled=true;button.textContent='Đang tạo thanh toán...'}try{const {data}=await PublicLookupService.createRenewal({renewalToken:item.renewalToken,months,returnUrl:window.location.href});item.orderCode=data.orderCode;item.paymentExpiresAt=Number(data.expiresAt);item.renewalMonths=months;const currentExpiry=data.currentExpiry||item.endDate||null;const proposedExpiry=data.proposedExpiry||item.renewalPeriods?.[months]?.proposedExpiry||null;panel.innerHTML=renewalPaymentCard(data,index,{months,currentExpiry,proposedExpiry});bindPayosCopyButtons(panel);startPolling(index);startRenewalCountdown(index);}catch(error){const target=panel.querySelector('[data-renew-error]');show(target,error.message);if(button){button.disabled=false;button.textContent='Tiếp tục thanh toán'}}}
async function refreshStatus(index){const item=lookupRows[index];const panel=document.querySelector(`[data-renew-panel="${index}"]`);const target=panel?.querySelector('[data-renew-status]');try{const {data}=await PublicLookupService.renewalStatus({renewalToken:item.renewalToken,orderCode:item.orderCode});if(data.status==='paid'){stopRenewalTimers(index);panel.innerHTML=renewalSuccessCard(data);return true}if(['expired','cancelled','failed'].includes(data.status)){stopRenewalTimers(index);renderTerminalPaymentStatus(panel,index,data.status);return true}if(target){target.className='public-renew-status is-pending';target.innerHTML='<span aria-hidden="true"></span> Đang chờ thanh toán'} }catch(error){if(target){target.className='public-renew-status is-failed';target.textContent='Chưa thể kiểm tra thanh toán. Vui lòng thử lại.'}}return false}
function startPolling(index){let attempts=0;stopRenewalTimers(index);const timer=window.setInterval(async()=>{attempts+=1;if(isRenewalExpired(lookupRows[index]?.paymentExpiresAt)||await refreshStatus(index)||attempts>=180){stopRenewalTimers(index)}},5000);renewalTimers.set(index,{poll:timer,countdown:0})}
function startRenewalCountdown(index){const tick=()=>{const item=lookupRows[index];const panel=document.querySelector(`[data-renew-panel="${index}"]`);const countdown=panel?.querySelector('[data-renew-countdown]');const remaining=getRemainingPaymentSeconds(item?.paymentExpiresAt);if(!countdown)return;if(remaining<=0){stopRenewalTimers(index);renderTerminalPaymentStatus(panel,index,'expired');return}countdown.classList.toggle('is-warning',remaining<=300);countdown.innerHTML=`<span>QR còn hiệu lực</span><strong>${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}</strong>`};tick();const timer=window.setInterval(tick,1000);const timers=renewalTimers.get(index)||{};timers.countdown=timer;renewalTimers.set(index,timers)}
function stopRenewalTimers(index){const timers=renewalTimers.get(index);if(timers?.poll)window.clearInterval(timers.poll);if(timers?.countdown)window.clearInterval(timers.countdown);renewalTimers.delete(index)}
async function recreateRenewal(index){const phone=document.getElementById('lookup-phone')?.value;const months=lookupRows[index]?.renewalMonths||1;if(!phone)return;const {data=[]}=await PublicLookupService.byPhone(phone);if(!data[index]?.renewalAvailable)return;lookupRows=data;openRenewal(index);await createRenewal(index,months)}
const ALLOWED_PUBLIC_MONTHS=new Set([1,3,6,12]);
export function renewalConfirmationCard(item,index,months){const period=item.renewalPeriods?.[months]||{};const total=Number(item.pricePerMonth)*months;return `<div class="public-renew-panel public-renew-confirmation"><header><span class="public-renew-eyebrow">Gia hạn Kiosk</span><h3>${escapeHtml(item.kiosk||'Kiosk')}</h3></header><div class="renew-money-row"><span>Giá dịch vụ</span><strong>${formatCurrency(item.pricePerMonth)} / tháng</strong></div><fieldset class="public-renew-duration"><legend>Thời hạn</legend>${[1,3,6,12].map(value=>`<label><input type="radio" name="public-renew-months" value="${value}" ${value===months?'checked':''}><span>${value} tháng</span></label>`).join('')}</fieldset><dl class="public-renew-preview"><div><dt>Ngày hết hạn hiện tại</dt><dd>${date(item.endDate)}</dd></div><div><dt>Ngày hết hạn dự kiến</dt><dd data-renew-proposed>${date(period.proposedExpiry)}</dd></div><div><dt>Tạm tính</dt><dd data-renew-subtotal>${formatCurrency(total)}</dd></div><div class="is-total"><dt>Thành tiền</dt><dd data-renew-total>${formatCurrency(total)}</dd></div></dl><p class="form-error hidden" data-renew-error role="alert"></p><button class="btn-primary" type="button" data-create-public-renewal="${index}">Tiếp tục thanh toán</button></div>`}
function updateRenewalConfirmation(item,panel,months){const period=item.renewalPeriods?.[months]||{};const total=Number(item.pricePerMonth)*months;panel.querySelector('[data-renew-proposed]').textContent=date(period.proposedExpiry);panel.querySelector('[data-renew-subtotal]').textContent=formatCurrency(total);panel.querySelector('[data-renew-total]').textContent=formatCurrency(total)}
export function renewalPaymentCard(data,index,{months,currentExpiry,proposedExpiry}){return `<div class="public-renew-panel public-renew-payment-card"><header><span class="public-renew-eyebrow">Thanh toán gia hạn</span><h3>${escapeHtml(data.kiosk||'Kiosk')}</h3></header><section class="public-renew-amount"><span>Số tiền cần thanh toán</span><strong>${formatCurrency(data.amount)}</strong></section><div data-renew-stale-actions class="public-renew-payment-columns"><div class="public-renew-qr-column">${renderPayosQr(data.qr,{className:'public-renew-qr'})}<p class="public-renew-scan-hint">Quét mã bằng ứng dụng ngân hàng</p><p class="payos-expiry-countdown" data-renew-countdown><span>QR còn hiệu lực</span><strong>--:--</strong></p>${data.checkoutUrl?`<a class="btn-primary public-renew-checkout" href="${escapeHtml(data.checkoutUrl)}" target="_blank" rel="noopener noreferrer">Mở trang thanh toán</a>`:''}</div>${renderManualTransfer(data.transfer)}</div><section class="public-renew-period" aria-label="Thông tin gia hạn"><h4>Thông tin gia hạn</h4><dl><div><dt>Thời hạn</dt><dd>${months} tháng</dd></div><div><dt>Ngày hết hạn hiện tại</dt><dd>${date(currentExpiry)}</dd></div><div><dt>Ngày hết hạn dự kiến</dt><dd>${date(proposedExpiry)}</dd></div></dl><p>Ngày dự kiến chỉ được áp dụng sau khi PayOS xác nhận thanh toán.</p></section><section class="public-renew-status-section"><div><span>Trạng thái</span><p class="public-renew-status is-pending" data-renew-status><span aria-hidden="true"></span> Đang chờ thanh toán</p></div><button class="btn-secondary" type="button" data-refresh-renewal="${index}">Kiểm tra thanh toán</button></section></div>`}
function renderManualTransfer(transfer){if(!transfer)return'';const rows=[['Ngân hàng',transfer.bankName||transfer.bin,false,false],['Số tài khoản',transfer.accountNumber,true,false],['Chủ tài khoản',transfer.accountName,false,false],['Số tiền',formatCurrency(transfer.amount),true,false],['Nội dung chuyển khoản',transfer.description,true,true]].filter(([,value])=>value);return `<section class="public-manual-transfer"><h4>Hoặc chuyển khoản thủ công</h4><dl>${rows.map(([label,value,copy,full])=>`<div class="public-transfer-field${full?' is-full':''}"><dt>${escapeHtml(label)}</dt><dd><strong>${escapeHtml(value)}</strong>${copy?`<button class="btn-secondary compact-button" type="button" data-copy-label="Sao chép" data-copy-text="${escapeHtml(value)}">Sao chép</button>`:''}</dd></div>`).join('')}</dl><p>Vui lòng chuyển đúng số tiền và nội dung để hệ thống có thể tự động xác nhận thanh toán.</p></section>`}
function renewalSuccessCard(data){return `<div class="renew-success public-renew-success"><div class="renew-success-icon">✓</div><h3>Gia hạn thành công</h3><p><strong>${escapeHtml(data.kiosk)}</strong></p><dl><div><dt>Đã thanh toán</dt><dd>${formatCurrency(data.amount)}</dd></div><div><dt>Thời hạn gia hạn</dt><dd>${Number(data.months)} tháng</dd></div><div><dt>Ngày hết hạn cũ</dt><dd>${date(data.currentExpiry)}</dd></div><div><dt>Ngày hết hạn mới</dt><dd>${date(data.newExpiry)}</dd></div></dl><p>Kiosk đã được cập nhật tự động.</p><button class="btn-primary" type="button" data-lookup-again>Tra cứu lại</button></div>`}
function renderTerminalPaymentStatus(panel,index,status){const expired=status==='expired';panel.querySelector('[data-renew-stale-actions]')?.classList.add('hidden');const section=panel.querySelector('.public-renew-status-section');if(section)section.innerHTML=`<div class="public-renew-terminal ${expired?'is-expired':'is-failed'}" role="status"><strong>${expired?'Mã thanh toán đã hết hạn.':'Thanh toán chưa hoàn tất'}</strong><p>${expired?'QR và liên kết thanh toán cũ không còn hiệu lực.':'Giao dịch đã bị hủy hoặc không thành công.'}</p><button class="btn-primary" type="button" data-new-public-renewal="${index}">Tạo mã thanh toán mới</button></div>`}
export function getRemainingPaymentSeconds(expiresAt,now=Date.now()){const expiry=Number(expiresAt);if(!Number.isFinite(expiry))return 0;return Math.max(0,Math.ceil(expiry-now/1000))}
function isRenewalExpired(expiresAt){return getRemainingPaymentSeconds(expiresAt)<=0}
function show(element,message){if(element){element.textContent=message;element.classList.remove('hidden')}}function remainingDays(value){if(!value)return 0;const end=new Date(`${value}T00:00:00`);const today=new Date();today.setHours(0,0,0,0);return Math.ceil((end-today)/86400000)}function date(value){const match=String(value||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return match?`${match[3]}/${match[2]}/${match[1]}`:'—'}function status(value,days){if(days<0)return'Hết hạn';return({active:'Đang hoạt động',warning:'Sắp hết hạn',pending:'Chờ duyệt'})[value]||'Đang cập nhật'}
