import { PublicLookupService } from '../services/PublicLookupService.js';
import { isValidPhone } from '../utils/formValidation.js';
import { formatCurrency } from '../utils/currency.js';
import { escapeHtml } from '../utils/html.js';
import { PublicSupport } from '../components/PublicSupport.js';

let lookupRows=[];
export function LookupPage(){return `<section class="portal-page narrow"><div class="portal-page-heading"><span>Tra cứu công khai</span><h1>Tra cứu Kiosk</h1><p>Nhập số điện thoại đã dùng khi đăng ký để xem thông tin Kiosk an toàn.</p></div><div class="lookup-guide"><strong>Cách sử dụng</strong><span>Nhập số điện thoại → bấm Tra cứu → xem kết quả bên dưới.</span></div><form id="lookup-form" class="lookup-form" novalidate><label class="form-group"><span>Số điện thoại đã đăng ký</span><input id="lookup-phone" class="form-control" type="tel" inputmode="tel" autocomplete="tel" placeholder="Ví dụ: 0888690346" required></label><button class="btn-primary" type="submit">Tra cứu</button></form><div id="lookup-message" class="form-error hidden" role="alert"></div><div id="lookup-results" class="lookup-results" aria-live="polite"></div>${PublicSupport()}</section>`}
LookupPage.afterRender=function(){lookupRows=[];document.getElementById('lookup-form')?.addEventListener('submit',lookup);document.getElementById('lookup-results')?.addEventListener('click',handleResultClick)};
async function lookup(event){event.preventDefault();const phone=document.getElementById('lookup-phone');const message=document.getElementById('lookup-message');const results=document.getElementById('lookup-results');const button=event.currentTarget.querySelector('button');message.classList.add('hidden');results.innerHTML='';if(!isValidPhone(phone.value)){show(message,'Số điện thoại phải có từ 9 đến 15 chữ số.');phone.focus();return}button.disabled=true;button.textContent='Đang tra cứu...';try{const {data=[]}=await PublicLookupService.byPhone(phone.value);lookupRows=data;results.innerHTML=data.length?data.map(resultCard).join(''):'<div class="lookup-empty"><strong>Chưa tìm thấy Kiosk</strong><span>Kiểm tra lại số điện thoại hoặc liên hệ hỗ trợ.</span></div>'}catch(error){show(message,error?.message||'Không thể tra cứu lúc này.')}finally{button.disabled=false;button.textContent='Tra cứu'}}
function resultCard(item,index){const days=remainingDays(item.endDate);return `<article class="lookup-card"><div><span>Kiosk</span><h2>${escapeHtml(item.kiosk||'Kiosk')}</h2></div><dl><div><dt>Danh mục</dt><dd>${escapeHtml(item.category||'—')}</dd></div><div><dt>Loại hình</dt><dd>${escapeHtml(item.businessType||'—')}</dd></div><div><dt>Ngày bắt đầu</dt><dd>${date(item.startDate)}</dd></div><div><dt>Ngày hết hạn</dt><dd>${date(item.endDate)}</dd></div><div><dt>Thời hạn còn lại</dt><dd>${days>=0?`${days} ngày`:'Đã hết hạn'}</dd></div><div><dt>Trạng thái</dt><dd><span class="status-pill">${status(item.status,days)}</span></dd></div></dl>${item.renewalAvailable?`<button class="btn-primary lookup-renew-button" type="button" data-renew-index="${index}">Gia hạn Kiosk</button><div data-renew-panel="${index}"></div>`:''}</article>`}
function handleResultClick(event){const renew=event.target.closest('[data-renew-index]');if(renew)return openRenewal(Number(renew.dataset.renewIndex));const create=event.target.closest('[data-create-public-renewal]');if(create)return createRenewal(Number(create.dataset.createPublicRenewal));const refresh=event.target.closest('[data-refresh-renewal]');if(refresh)return refreshStatus(Number(refresh.dataset.refreshRenewal));}
function openRenewal(index){const item=lookupRows[index];const panel=document.querySelector(`[data-renew-panel="${index}"]`);if(!item||!panel)return;panel.innerHTML=`<div class="public-renew-panel"><h3>Gia hạn ${escapeHtml(item.kiosk)}</h3><label class="form-group"><span>Thời hạn</span><select class="form-control" data-renew-months><option value="1">1 tháng</option><option value="3">3 tháng</option><option value="6">6 tháng</option><option value="12">12 tháng</option></select></label><div class="renew-money-row"><span>Giá</span><strong data-renew-price>${formatCurrency(item.pricePerMonth)} / tháng</strong></div><div class="renew-total"><span>TỔNG</span><strong data-renew-total>${formatCurrency(item.pricePerMonth)}</strong></div><p class="form-error hidden" data-renew-error></p><button class="btn-primary" type="button" data-create-public-renewal="${index}">Xác nhận &amp; Tạo QR PayOS</button></div>`;panel.querySelector('[data-renew-months]')?.addEventListener('change',e=>{panel.querySelector('[data-renew-total]').textContent=formatCurrency(Number(item.pricePerMonth)*Number(e.target.value))});}
async function createRenewal(index){const item=lookupRows[index];const panel=document.querySelector(`[data-renew-panel="${index}"]`);const button=panel?.querySelector('[data-create-public-renewal]');const months=Number(panel?.querySelector('[data-renew-months]')?.value);if(!item||!button)return;button.disabled=true;button.textContent='Đang tạo QR...';try{const {data}=await PublicLookupService.createRenewal({renewalToken:item.renewalToken,months,returnUrl:window.location.href});item.orderCode=data.orderCode;panel.innerHTML=`<div class="public-renew-panel public-renew-payment"><h3>Thanh toán đang chờ</h3><strong>${formatCurrency(data.amount)}</strong>${data.qrCode?`<img src="${escapeHtml(data.qrCode)}" alt="QR PayOS">`:''}${data.checkoutUrl?`<a class="btn-primary" href="${escapeHtml(data.checkoutUrl)}" target="_blank" rel="noopener noreferrer">Mở trang thanh toán</a>`:''}<p>Chỉ sau khi PayOS xác nhận, Kiosk mới được gia hạn.</p><button class="btn-secondary" type="button" data-refresh-renewal="${index}">Kiểm tra thanh toán</button><div data-renew-status></div></div>`;startPolling(index);}catch(error){const target=panel.querySelector('[data-renew-error]');show(target,error.message);button.disabled=false;button.textContent='Xác nhận & Tạo QR PayOS'}}
async function refreshStatus(index){const item=lookupRows[index];const panel=document.querySelector(`[data-renew-panel="${index}"]`);const target=panel?.querySelector('[data-renew-status]');try{const {data}=await PublicLookupService.renewalStatus({renewalToken:item.renewalToken,orderCode:item.orderCode});if(data.status==='completed'){panel.innerHTML=`<div class="renew-success"><div class="renew-success-icon">✓</div><h3>Gia hạn thành công</h3><p><strong>${escapeHtml(data.kiosk)}</strong></p><p>Hạn mới: <strong>${date(data.newExpiry)}</strong></p><p>Số tiền: <strong>${formatCurrency(data.amount)}</strong></p><p>Thanh toán thành công</p></div>`;return true}target.textContent='Thanh toán vẫn đang chờ PayOS xác nhận.'}catch(error){target.textContent=error.message}return false}
function startPolling(index){let attempts=0;const timer=window.setInterval(async()=>{attempts+=1;if(await refreshStatus(index)||attempts>=20)window.clearInterval(timer)},5000)}
function show(element,message){if(element){element.textContent=message;element.classList.remove('hidden')}}function remainingDays(value){if(!value)return 0;const end=new Date(`${value}T00:00:00`);const today=new Date();today.setHours(0,0,0,0);return Math.ceil((end-today)/86400000)}function date(value){if(!value)return'—';return new Intl.DateTimeFormat('vi-VN').format(new Date(`${value}T00:00:00`))}function status(value,days){if(days<0)return'Hết hạn';return({active:'Đang hoạt động',warning:'Sắp hết hạn',pending:'Chờ duyệt'})[value]||'Đang cập nhật'}
