-- Forward-only batch ownership for public registrations. Historical request,
-- payment and PayOS rows remain unchanged and continue through the legacy path.

create table if not exists public.registration_batches (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.customers(id) on delete restrict,
  payment_id bigint references public.payments(id) on delete restrict,
  phone text not null,
  status text not null default 'pending' check (status in ('pending','approved','cancelled','rejected')),
  total_amount numeric not null default 0 check (total_amount >= 0),
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  approved_at timestamptz
);

create table if not exists public.registration_batch_items (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.registration_batches(id) on delete restrict,
  registration_request_id bigint not null references public.registration_requests(id) on delete restrict,
  kiosk_id bigint not null references public.kiosks(id) on delete restrict,
  business_type_id bigint not null references public.business_types(id) on delete restrict,
  months integer not null check (months > 0),
  price_per_month numeric not null check (price_per_month >= 0),
  discount numeric not null default 0 check (discount >= 0),
  total_amount numeric not null check (total_amount > 0),
  start_date date,
  end_date date,
  created_at timestamptz not null default pg_catalog.now(),
  unique (registration_request_id),
  unique (batch_id, kiosk_id)
);

alter table public.registration_batches enable row level security;
alter table public.registration_batch_items enable row level security;
alter table public.registration_requests add column if not exists registration_batch_id bigint references public.registration_batches(id) on delete restrict;
alter table public.payments add column if not exists registration_batch_id bigint references public.registration_batches(id) on delete restrict;

create unique index if not exists registration_batches_payment_uidx on public.registration_batches(payment_id) where payment_id is not null;
create unique index if not exists payments_registration_batch_uidx on public.payments(registration_batch_id) where registration_batch_id is not null;
create index if not exists registration_requests_batch_idx on public.registration_requests(registration_batch_id);
create index if not exists registration_batch_items_batch_idx on public.registration_batch_items(batch_id);

create or replace function public.prepare_registration_batch_for_payos(request_ids_input bigint[], phone_input text)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare
  normalized_phone text:=pg_catalog.regexp_replace(pg_catalog.coalesce(phone_input,''),'[^0-9+]','','g');
  request_count integer;
  request_record public.registration_requests%rowtype;
  batch_record public.registration_batches%rowtype;
  customer_record public.customers%rowtype;
  kiosk_record public.kiosks%rowtype;
  package_record public.business_types%rowtype;
  payment_record public.payments%rowtype;
  first_kiosk_id bigint;
  authoritative_total numeric:=0;
  item_total numeric;
  group_member_base_url text;
  result_items jsonb:='[]'::jsonb;
  batch_key text;
begin
  if pg_catalog.coalesce(auth.jwt()->>'role','')<>'service_role' then raise exception 'Chỉ API server được chuẩn bị thanh toán đăng ký.' using errcode='42501'; end if;
  request_count:=pg_catalog.coalesce(pg_catalog.array_length(request_ids_input,1),0);
  if request_count<1 or request_count>20 then raise exception 'Lô đăng ký phải có từ 1 đến 20 Kiosk.' using errcode='22023'; end if;
  if normalized_phone='' then raise exception 'Số điện thoại xác nhận không hợp lệ.' using errcode='22023'; end if;
  if (select count(distinct value) from pg_catalog.unnest(request_ids_input) value)<>request_count then raise exception 'Danh sách yêu cầu đăng ký bị trùng.' using errcode='22023'; end if;
  batch_key:='registration-batch:'||(select pg_catalog.string_agg(value::text,',' order by value) from pg_catalog.unnest(request_ids_input) value);
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(batch_key,0));

  perform 1 from public.registration_requests where id=any(request_ids_input) order by id for update;
  select count(*) into request_count from public.registration_requests where id=any(request_ids_input);
  if request_count<>pg_catalog.array_length(request_ids_input,1) then raise exception 'Không tìm thấy đầy đủ yêu cầu đăng ký.' using errcode='P0002'; end if;
  if exists(select 1 from public.registration_requests where id=any(request_ids_input) and pg_catalog.regexp_replace(pg_catalog.coalesce(phone,''),'[^0-9+]','','g')<>normalized_phone) then raise exception 'Số điện thoại không khớp lô đăng ký.' using errcode='42501'; end if;
  if exists(select 1 from public.registration_requests where id=any(request_ids_input) and pg_catalog.lower(pg_catalog.coalesce(status,'pending')) not in ('pending','approved')) then raise exception 'Lô đăng ký không còn có thể thanh toán.' using errcode='22023'; end if;

  select b.* into batch_record from public.registration_batches b join public.registration_requests r on r.registration_batch_id=b.id where r.id=any(request_ids_input) order by b.id limit 1 for update of b;
  if found then
    if exists(select 1 from public.registration_requests where id=any(request_ids_input) and registration_batch_id is distinct from batch_record.id) then raise exception 'Yêu cầu đã thuộc lô đăng ký khác.' using errcode='23505'; end if;
    select * into payment_record from public.payments where id=batch_record.payment_id for update;
    return jsonb_build_object('batch',to_jsonb(batch_record),'payment',to_jsonb(payment_record),'items',(select pg_catalog.coalesce(jsonb_agg(jsonb_build_object('requestId',i.registration_request_id,'kioskId',i.kiosk_id,'name',k.facebook_name,'months',i.months,'pricePerMonth',i.price_per_month,'discount',i.discount,'totalAmount',i.total_amount)), '[]'::jsonb) from public.registration_batch_items i join public.kiosks k on k.id=i.kiosk_id where i.batch_id=batch_record.id),'reused',true);
  end if;

  select * into customer_record from public.customers where pg_catalog.regexp_replace(pg_catalog.coalesce(phone,''),'[^0-9+]','','g')=normalized_phone order by id limit 1 for update;
  if not found then
    select * into request_record from public.registration_requests where id=any(request_ids_input) order by id limit 1;
    insert into public.customers(facebook_name,facebook_id,facebook_link,phone,address,status,total_kiosks,total_paid,note)
    values(request_record.facebook_name,nullif(request_record.facebook_id,''),request_record.facebook_link,request_record.phone,request_record.address,'pending',0,0,request_record.note)
    returning * into customer_record;
  end if;
  insert into public.registration_batches(customer_id,phone,status,total_amount) values(customer_record.id,normalized_phone,'pending',0) returning * into batch_record;
  select case when nullif(pg_catalog.trim(s.value),'')~'^[0-9]+$' then 'https://www.facebook.com/groups/'||pg_catalog.trim(s.value)||'/user/' else null end into group_member_base_url from public.settings s where s.key='facebook_group_id';

  for request_record in select * from public.registration_requests where id=any(request_ids_input) order by id for update loop
    select * into package_record from public.business_types where id=request_record.business_type_id and is_active=true for share;
    if not found or package_record.price_per_month is null or package_record.price_per_month<0 then raise exception 'Loại hình kinh doanh không tồn tại, không hoạt động hoặc thiếu giá.' using errcode='22023'; end if;
    if request_record.months is null or request_record.months<1 or pg_catalog.coalesce(request_record.discount,0)<>0 then raise exception 'Thời hạn không hợp lệ hoặc đăng ký công khai chứa giảm giá không được phép.' using errcode='22023'; end if;
    item_total:=package_record.price_per_month*request_record.months;
    if item_total<=0 or request_record.total_amount is distinct from item_total then raise exception 'Tổng tiền Kiosk không khớp giá hiện hành.' using errcode='22023'; end if;

    if request_record.kiosk_id is not null then select * into kiosk_record from public.kiosks where id=request_record.kiosk_id for update; else kiosk_record:=null; end if;
    if kiosk_record.id is null then
      insert into public.kiosks(customer_id,facebook_name,facebook_id,facebook_link,facebook_group_link,category_id,business_type_id,service_name,start_date,end_date,status,auto_approve,total_paid,kiosk_total_paid,last_payment_date,note,is_primary)
      values(customer_record.id,request_record.facebook_name,nullif(request_record.facebook_id,''),request_record.facebook_link,case when group_member_base_url is null or nullif(request_record.facebook_id,'') is null then null else group_member_base_url||request_record.facebook_id||'/' end,package_record.category_id,package_record.id,package_record.name,null,null,'pending',false,0,0,null,request_record.note,not exists(select 1 from public.kiosks k where k.customer_id=customer_record.id and k.is_primary)) returning * into kiosk_record;
    elsif kiosk_record.customer_id<>customer_record.id then raise exception 'Kiosk không thuộc khách hàng của lô đăng ký.' using errcode='23505'; end if;
    first_kiosk_id:=pg_catalog.coalesce(first_kiosk_id,kiosk_record.id);
    insert into public.registration_batch_items(batch_id,registration_request_id,kiosk_id,business_type_id,months,price_per_month,discount,total_amount)
    values(batch_record.id,request_record.id,kiosk_record.id,package_record.id,request_record.months,package_record.price_per_month,pg_catalog.coalesce(request_record.discount,0),item_total);
    update public.registration_requests set customer_id=customer_record.id,kiosk_id=kiosk_record.id,registration_batch_id=batch_record.id,metadata=pg_catalog.coalesce(metadata,'{}'::jsonb)||jsonb_build_object('materialized_for_batch_payos_at',pg_catalog.now()) where id=request_record.id;
    authoritative_total:=authoritative_total+item_total;
    result_items:=result_items||jsonb_build_array(jsonb_build_object('requestId',request_record.id,'kioskId',kiosk_record.id,'name',kiosk_record.facebook_name,'months',request_record.months,'pricePerMonth',package_record.price_per_month,'discount',pg_catalog.coalesce(request_record.discount,0),'totalAmount',item_total));
  end loop;
  if authoritative_total<=0 then raise exception 'Tổng tiền lô đăng ký không hợp lệ.' using errcode='22023'; end if;
  insert into public.payments(customer_id,kiosk_id,start_date,end_date,months,price_per_month,discount,total_amount,payment_method,payment_status,transaction_type,note,payment_intent_key,registration_batch_id)
  values(customer_record.id,first_kiosk_id,null,null,1,authoritative_total,0,authoritative_total,'transfer','pending','standard','Public registration batch #'||batch_record.id,'registration-batch:'||batch_record.id,batch_record.id) returning * into payment_record;
  update public.registration_batches set payment_id=payment_record.id,total_amount=authoritative_total,updated_at=pg_catalog.now() where id=batch_record.id returning * into batch_record;
  update public.registration_requests set payment_id=payment_record.id where registration_batch_id=batch_record.id;
  update public.customers c set total_kiosks=(select count(*) from public.kiosks k where k.customer_id=c.id) where c.id=customer_record.id;
  return jsonb_build_object('batch',to_jsonb(batch_record),'payment',to_jsonb(payment_record),'items',result_items,'reused',false);
end;$function$;

revoke all on function public.prepare_registration_batch_for_payos(bigint[],text) from public,anon,authenticated;
grant execute on function public.prepare_registration_batch_for_payos(bigint[],text) to service_role;

create or replace function private.confirm_registration_batch_from_payos(payment_id_input bigint,reason_input text default 'PayOS paid')
returns jsonb language plpgsql security definer set search_path='' as $function$
declare payment_record public.payments%rowtype; batch_record public.registration_batches%rowtype; item_record record; confirmation_timestamp timestamptz:=pg_catalog.now(); confirmation_date date:=(pg_catalog.now() at time zone 'Asia/Ho_Chi_Minh')::date; calculated_end date; item_count integer:=0;
begin
  select * into payment_record from public.payments where id=payment_id_input for update;
  if not found or payment_record.registration_batch_id is null then raise exception 'Không tìm thấy thanh toán lô đăng ký.' using errcode='P0002'; end if;
  select * into batch_record from public.registration_batches where id=payment_record.registration_batch_id for update;
  if not found or batch_record.payment_id<>payment_record.id then raise exception 'Liên kết thanh toán lô đăng ký không hợp lệ.' using errcode='22023'; end if;
  if payment_record.payment_status<>'pending' or batch_record.status<>'pending' then raise exception 'Lô đăng ký không còn Pending.' using errcode='22023'; end if;
  if payment_record.total_amount<>batch_record.total_amount or batch_record.total_amount<>(select pg_catalog.coalesce(sum(total_amount),0) from public.registration_batch_items where batch_id=batch_record.id) then raise exception 'Tổng tiền lô đăng ký không khớp.' using errcode='22023'; end if;
  perform 1 from public.registration_batch_items i join public.kiosks k on k.id=i.kiosk_id join public.registration_requests r on r.id=i.registration_request_id where i.batch_id=batch_record.id order by i.id for update of i,k,r;
  for item_record in select i.*,k.facebook_name from public.registration_batch_items i join public.kiosks k on k.id=i.kiosk_id where i.batch_id=batch_record.id order by i.id loop
    calculated_end:=(confirmation_date+pg_catalog.make_interval(months=>item_record.months)-interval '1 day')::date;
    update public.registration_batch_items set start_date=confirmation_date,end_date=calculated_end where id=item_record.id;
    update public.kiosks set status='active',start_date=confirmation_date,end_date=calculated_end where id=item_record.kiosk_id;
    update public.registration_requests set status='approved',requested_start_date=confirmation_date,requested_end_date=calculated_end,reviewed_at=pg_catalog.coalesce(reviewed_at,confirmation_timestamp),updated_at=confirmation_timestamp where id=item_record.registration_request_id;
    item_count:=item_count+1;
  end loop;
  if item_count<1 then raise exception 'Lô đăng ký không có Kiosk.' using errcode='22023'; end if;
  perform pg_catalog.set_config('app.payment_workflow_action','confirm',true);
  update public.payments set payment_status='completed',confirmed_by=null,confirmed_at=confirmation_timestamp where id=payment_record.id returning * into payment_record;
  update public.registration_batches set status='approved',approved_at=confirmation_timestamp,updated_at=confirmation_timestamp where id=batch_record.id returning * into batch_record;
  update public.customers set status=case when pg_catalog.lower(pg_catalog.coalesce(status,''))='pending' then 'active' else status end,total_kiosks=(select count(*) from public.kiosks k where k.customer_id=batch_record.customer_id) where id=batch_record.customer_id;
  perform private.write_ttc_audit('Payment','confirm_payos_batch','registration_batches',batch_record.id::text,null,jsonb_build_object('payment_id',payment_record.id,'amount',payment_record.total_amount,'kiosk_count',item_count),reason_input);
  return jsonb_build_object('payment',to_jsonb(payment_record),'batch',to_jsonb(batch_record),'items',(select jsonb_agg(jsonb_build_object('id',k.id,'name',k.facebook_name,'startDate',i.start_date,'endDate',i.end_date,'status',k.status) order by i.id) from public.registration_batch_items i join public.kiosks k on k.id=i.kiosk_id where i.batch_id=batch_record.id));
end;$function$;
revoke all on function private.confirm_registration_batch_from_payos(bigint,text) from public,anon,authenticated;
grant execute on function private.confirm_registration_batch_from_payos(bigint,text) to service_role;

create or replace function public.record_registration_payos_order(payment_id_input bigint,order_code_input bigint,amount_input numeric,description_input text,checkout_url_input text default null,qr_code_input text default null,payment_link_id_input text default null,provider_payload_input jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare order_record public.payos_orders%rowtype;
begin
  if pg_catalog.coalesce(auth.jwt()->>'role','')<>'service_role' then raise exception 'Chỉ API server được ghi PayOS order đăng ký.' using errcode='42501'; end if;
  if not exists(select 1 from public.payments p join public.registration_batches b on b.payment_id=p.id where p.id=payment_id_input and p.registration_batch_id=b.id and p.payment_status='pending' and b.status='pending' and p.total_amount=b.total_amount and p.total_amount=amount_input) then raise exception 'Thanh toán lô đăng ký không hợp lệ.' using errcode='22023'; end if;
  order_record:=private.reserve_crm_payos_order(payment_id_input,order_code_input,amount_input,description_input,checkout_url_input,qr_code_input,payment_link_id_input,provider_payload_input);
  return to_jsonb(order_record);
end;$function$;
revoke all on function public.record_registration_payos_order(bigint,bigint,numeric,text,text,text,text,jsonb) from public,anon,authenticated;
grant execute on function public.record_registration_payos_order(bigint,bigint,numeric,text,text,text,text,jsonb) to service_role;

create or replace function public.handle_payos_webhook(order_code_input bigint,amount_input numeric,payment_link_id_input text default null,reference_input text default null,provider_payload_input jsonb default '{}'::jsonb,signature_input text default null,event_key_input text default null)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare order_record public.payos_orders%rowtype; payment_record public.payments%rowtype; event_record public.payos_webhook_events%rowtype; rpc_result jsonb; normalized_event_key text:=pg_catalog.coalesce(nullif(pg_catalog.trim(event_key_input),''),'payos:'||order_code_input::text||':'||pg_catalog.coalesce(nullif(pg_catalog.trim(reference_input),''),'paid'));
begin
  insert into public.payos_webhook_events(event_key,order_code,signature,payload) values(normalized_event_key,order_code_input,nullif(pg_catalog.trim(signature_input),''),pg_catalog.coalesce(provider_payload_input,'{}'::jsonb)) on conflict(event_key) do update set payload=excluded.payload returning * into event_record;
  if event_record.status='processed' then return jsonb_build_object('already_processed',true,'event',to_jsonb(event_record)); end if;
  select * into order_record from public.payos_orders where order_code=order_code_input for update;
  if not found then raise exception 'Không tìm thấy PayOS order.' using errcode='P0002'; end if;
  if order_record.amount<>amount_input then raise exception 'Số tiền webhook không khớp PayOS order.' using errcode='22023'; end if;
  if order_record.status='paid' then update public.payos_webhook_events set status='processed',processed_at=pg_catalog.now() where id=event_record.id returning * into event_record; return jsonb_build_object('already_processed',true,'order',to_jsonb(order_record),'event',to_jsonb(event_record)); end if;
  if order_record.purpose='crm_payment' then
    select * into payment_record from public.payments where id=order_record.payment_id for update;
    if not found or payment_record.total_amount<>amount_input then raise exception 'Số tiền webhook không khớp thanh toán.' using errcode='22023'; end if;
    if payment_record.payment_status='completed' then update public.payos_orders set status='paid',active_slot=null,confirmed_at=pg_catalog.coalesce(confirmed_at,pg_catalog.now()),processed_at=pg_catalog.coalesce(processed_at,pg_catalog.now()),provider_payload=provider_payload||pg_catalog.coalesce(provider_payload_input,'{}'::jsonb),updated_at=pg_catalog.now() where id=order_record.id returning * into order_record; update public.payos_webhook_events set status='processed',processed_at=pg_catalog.now(),error='Payment already completed; paid sibling requires reconciliation.' where id=event_record.id returning * into event_record; return jsonb_build_object('already_processed',true,'reconciliation_required',true,'order',to_jsonb(order_record),'event',to_jsonb(event_record)); end if;
    if payment_record.payment_status<>'pending' then raise exception 'Thanh toán không còn Pending.' using errcode='22023'; end if;
    if payment_record.registration_batch_id is not null then rpc_result:=private.confirm_registration_batch_from_payos(payment_record.id,'PayOS paid: '||pg_catalog.coalesce(nullif(pg_catalog.trim(reference_input),''),order_record.order_code::text)); else rpc_result:=private.confirm_crm_payment_from_payos(payment_record.id,'PayOS paid: '||pg_catalog.coalesce(nullif(pg_catalog.trim(reference_input),''),order_record.order_code::text)); update public.registration_requests set status='approved',reviewed_at=pg_catalog.coalesce(reviewed_at,pg_catalog.now()),updated_at=pg_catalog.now() where payment_id=payment_record.id and status='pending'; end if;
    update public.payos_orders set status='cancelled',active_slot=null,processed_at=pg_catalog.coalesce(processed_at,pg_catalog.now()),updated_at=pg_catalog.now() where payment_id=payment_record.id and id<>order_record.id and status='pending';
  elsif order_record.purpose='wallet_topup' then rpc_result:=private.post_wallet_ledger(order_record.wallet_user_id,order_record.amount,'admin_adjustment','payos_orders',order_record.id::text,'payos-paid:'||order_record.order_code::text,'Nạp xu PayOS','PayOS paid: '||pg_catalog.coalesce(nullif(pg_catalog.trim(reference_input),''),order_record.order_code::text),jsonb_build_object('source','payos','order_code',order_record.order_code),null,'system');
  else raise exception 'Mục đích PayOS không hợp lệ.' using errcode='22023'; end if;
  update public.payos_orders set status='paid',active_slot=null,payment_link_id=pg_catalog.coalesce(nullif(pg_catalog.trim(payment_link_id_input),''),payment_link_id),provider_payload=provider_payload||pg_catalog.coalesce(provider_payload_input,'{}'::jsonb),confirmed_at=pg_catalog.coalesce(confirmed_at,pg_catalog.now()),processed_at=pg_catalog.now(),updated_at=pg_catalog.now() where id=order_record.id returning * into order_record;
  update public.payos_webhook_events set status='processed',processed_at=pg_catalog.now() where id=event_record.id returning * into event_record;
  return jsonb_build_object('order',to_jsonb(order_record),'event',to_jsonb(event_record),'result',rpc_result,'already_processed',false);
end;$function$;
revoke all on function public.handle_payos_webhook(bigint,numeric,text,text,jsonb,text,text) from public,anon,authenticated;
grant execute on function public.handle_payos_webhook(bigint,numeric,text,text,jsonb,text,text) to service_role;
