create table if not exists public.payos_orders (
  id bigint generated by default as identity primary key,
  order_code bigint not null unique,
  purpose text not null,
  payment_id bigint references public.payments(id) on delete restrict,
  wallet_user_id uuid references public.user_profiles(user_id) on delete restrict,
  amount numeric(14, 2) not null,
  description text not null,
  checkout_url text,
  qr_code text,
  payment_link_id text,
  status text not null default 'pending',
  provider_payload jsonb not null default '{}'::jsonb,
  created_by uuid default auth.uid(),
  confirmed_at timestamptz,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payos_orders_purpose_check
    check (purpose in ('crm_payment', 'wallet_topup')),
  constraint payos_orders_status_check
    check (status in ('pending', 'paid', 'cancelled', 'expired', 'failed')),
  constraint payos_orders_amount_check
    check (amount > 0),
  constraint payos_orders_target_check
    check (
      (purpose = 'crm_payment' and payment_id is not null and wallet_user_id is null)
      or
      (purpose = 'wallet_topup' and wallet_user_id is not null and payment_id is null)
    )
);

alter table public.payments
  add column if not exists transaction_type text not null default 'standard';

create table if not exists public.payos_webhook_events (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  order_code bigint,
  signature text,
  status text not null default 'received',
  payload jsonb not null default '{}'::jsonb,
  error text,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint payos_webhook_events_status_check
    check (status in ('received', 'processed', 'ignored', 'failed'))
);

create index if not exists idx_payos_orders_payment_id
  on public.payos_orders(payment_id);
create index if not exists idx_payos_orders_wallet_user_id
  on public.payos_orders(wallet_user_id);
create index if not exists idx_payos_orders_status_created
  on public.payos_orders(status, created_at desc);
create index if not exists idx_payos_webhook_events_order_code
  on public.payos_webhook_events(order_code);

alter table public.payos_orders enable row level security;
alter table public.payos_webhook_events enable row level security;

drop policy if exists "payos_orders_staff_read" on public.payos_orders;
create policy "payos_orders_staff_read"
on public.payos_orders
for select
to authenticated
using (
  wallet_user_id = auth.uid()
  or public.has_active_staff_permission('payments')
  or public.has_active_staff_permission('admin-ttc')
);

drop policy if exists "payos_webhook_events_staff_read" on public.payos_webhook_events;
create policy "payos_webhook_events_staff_read"
on public.payos_webhook_events
for select
to authenticated
using (
  public.has_active_staff_permission('payments')
  or public.has_active_staff_permission('admin-ttc')
);

create or replace function private.current_staff_has_payos_access()
returns boolean
language sql
security definer
set search_path = ''
as $function$
  select coalesce(public.has_active_staff_permission('payments'), false)
    or coalesce(public.has_active_staff_permission('admin-ttc'), false);
$function$;

create or replace function public.record_payos_payment_link(
  purpose_input text,
  payment_id_input bigint,
  wallet_user_id_input uuid,
  order_code_input bigint,
  amount_input numeric,
  description_input text,
  checkout_url_input text default null,
  qr_code_input text default null,
  payment_link_id_input text default null,
  provider_payload_input jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  order_record public.payos_orders%rowtype;
  payment_record public.payments%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Bạn phải đăng nhập để tạo thanh toán PayOS.' using errcode = '42501';
  end if;

  if purpose_input = 'crm_payment' then
    if not private.current_staff_has_payos_access() then
      raise exception 'Không có quyền tạo thanh toán CRM qua PayOS.' using errcode = '42501';
    end if;

    select *
    into payment_record
    from public.payments
    where id = payment_id_input;

    if not found then
      raise exception 'Không tìm thấy thanh toán CRM.' using errcode = '22023';
    end if;
    if lower(coalesce(payment_record.payment_status, '')) <> 'pending' then
      raise exception 'Chỉ tạo PayOS cho thanh toán Pending.' using errcode = '22023';
    end if;
    if coalesce(payment_record.total_amount, 0) <> amount_input then
      raise exception 'Số tiền PayOS không khớp thanh toán CRM.' using errcode = '22023';
    end if;
  elsif purpose_input = 'wallet_topup' then
    if wallet_user_id_input <> auth.uid() and not private.current_staff_has_payos_access() then
      raise exception 'Không có quyền tạo thanh toán nạp xu cho user khác.' using errcode = '42501';
    end if;
    if not exists (
      select 1 from public.user_profiles up where up.user_id = wallet_user_id_input
    ) then
      raise exception 'Không tìm thấy hồ sơ user nhận xu.' using errcode = '22023';
    end if;
  else
    raise exception 'Mục đích PayOS không hợp lệ.' using errcode = '22023';
  end if;

  insert into public.payos_orders(
    order_code,
    purpose,
    payment_id,
    wallet_user_id,
    amount,
    description,
    checkout_url,
    qr_code,
    payment_link_id,
    provider_payload,
    created_by
  )
  values(
    order_code_input,
    purpose_input,
    payment_id_input,
    wallet_user_id_input,
    amount_input,
    nullif(trim(description_input), ''),
    nullif(trim(checkout_url_input), ''),
    nullif(trim(qr_code_input), ''),
    nullif(trim(payment_link_id_input), ''),
    coalesce(provider_payload_input, '{}'::jsonb),
    auth.uid()
  )
  on conflict (order_code) do update
  set
    checkout_url = excluded.checkout_url,
    qr_code = excluded.qr_code,
    payment_link_id = excluded.payment_link_id,
    provider_payload = excluded.provider_payload,
    updated_at = now()
  where public.payos_orders.status = 'pending'
  returning * into order_record;

  return to_jsonb(order_record);
end;
$function$;

create or replace function private.confirm_crm_payment_from_payos(
  payment_id_input bigint,
  reason_input text default 'PayOS paid'
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  payment_record public.payments%rowtype;
  before_record public.payments%rowtype;
  customer_record public.customers%rowtype;
  kiosk_record public.kiosks%rowtype;
  package_record public.business_types%rowtype;
  confirmation_timestamp timestamptz := now();
  confirmation_date date := (now() at time zone 'Asia/Ho_Chi_Minh')::date;
  effective_start_date date;
  calculated_end_date date;
  expected_total numeric;
begin
  select *
  into payment_record
  from public.payments
  where id = payment_id_input
  for update;

  if not found then
    raise exception 'Không tìm thấy thanh toán.';
  end if;

  if lower(payment_record.payment_status) <> 'pending' then
    raise exception 'Chỉ thanh toán Pending mới được xác nhận.';
  end if;

  if payment_record.transaction_type <> 'standard' then
    raise exception 'Giao dịch điều chỉnh không dùng xác nhận PayOS.';
  end if;

  before_record := payment_record;

  select *
  into customer_record
  from public.customers
  where id = payment_record.customer_id
  for update;

  if not found then
    raise exception 'Khách hàng của thanh toán không tồn tại.';
  end if;

  select *
  into kiosk_record
  from public.kiosks
  where id = payment_record.kiosk_id
  for update;

  if not found then
    raise exception 'Kiosk của thanh toán không tồn tại.';
  end if;

  if kiosk_record.customer_id <> customer_record.id then
    raise exception 'Kiosk không thuộc khách hàng của thanh toán.';
  end if;

  select *
  into package_record
  from public.business_types
  where id = kiosk_record.business_type_id
    and is_active = true;

  if not found then
    raise exception 'Gói dịch vụ không tồn tại hoặc đã ngừng hoạt động.';
  end if;

  if payment_record.months is null or payment_record.months < 1 then
    raise exception 'Số tháng thanh toán không hợp lệ.';
  end if;

  if payment_record.price_per_month is null or payment_record.price_per_month < 0
    or payment_record.discount is null or payment_record.discount < 0
    or payment_record.total_amount is null or payment_record.total_amount <= 0 then
    raise exception 'Giá trị tài chính của thanh toán không hợp lệ.';
  end if;

  expected_total := payment_record.price_per_month * payment_record.months
    - payment_record.discount;

  if payment_record.total_amount <> expected_total then
    raise exception 'Tổng tiền không khớp giá, số tháng và giảm giá.';
  end if;

  if lower(kiosk_record.status) = 'active'
    and kiosk_record.end_date is not null
    and kiosk_record.end_date >= confirmation_date then
    effective_start_date := kiosk_record.end_date + 1;
  else
    effective_start_date := confirmation_date;
  end if;

  calculated_end_date := (
    effective_start_date + make_interval(months => payment_record.months)
  )::date;

  perform set_config('app.payment_workflow_action', 'confirm', true);

  update public.payments
  set
    payment_status = 'completed',
    confirmed_by = null,
    confirmed_at = confirmation_timestamp,
    start_date = effective_start_date,
    end_date = calculated_end_date
  where id = payment_record.id
  returning * into payment_record;

  update public.kiosks
  set
    status = 'active',
    start_date = effective_start_date,
    end_date = calculated_end_date
  where id = kiosk_record.id;

  update public.customers
  set
    status = case
      when lower(coalesce(status, '')) = 'pending' then 'active'
      else status
    end,
    total_kiosks = (
      select count(*) from public.kiosks k where k.customer_id = customer_record.id
    )
  where id = customer_record.id;

  perform private.write_ttc_audit(
    'Payment',
    'confirm_payos',
    'payments',
    payment_record.id::text,
    to_jsonb(before_record),
    to_jsonb(payment_record),
    reason_input
  );

  return jsonb_build_object(
    'payment', to_jsonb(payment_record),
    'kiosk', (
      select to_jsonb(k) from public.kiosks k where k.id = kiosk_record.id
    ),
    'customer', (
      select to_jsonb(c) from public.customers c where c.id = customer_record.id
    )
  );
end;
$function$;

create or replace function public.handle_payos_webhook(
  order_code_input bigint,
  amount_input numeric,
  payment_link_id_input text default null,
  reference_input text default null,
  provider_payload_input jsonb default '{}'::jsonb,
  signature_input text default null,
  event_key_input text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  order_record public.payos_orders%rowtype;
  event_record public.payos_webhook_events%rowtype;
  normalized_event_key text := coalesce(
    nullif(trim(event_key_input), ''),
    'payos:' || order_code_input::text || ':' || coalesce(nullif(trim(reference_input), ''), 'paid')
  );
  rpc_result jsonb;
begin
  insert into public.payos_webhook_events(
    event_key,
    order_code,
    signature,
    payload
  )
  values(
    normalized_event_key,
    order_code_input,
    nullif(trim(signature_input), ''),
    coalesce(provider_payload_input, '{}'::jsonb)
  )
  on conflict (event_key) do update
  set payload = excluded.payload
  returning * into event_record;

  if event_record.status = 'processed' then
    return jsonb_build_object('already_processed', true, 'event', to_jsonb(event_record));
  end if;

  select *
  into order_record
  from public.payos_orders
  where order_code = order_code_input
  for update;

  if not found then
    update public.payos_webhook_events
    set status = 'ignored', error = 'Không tìm thấy PayOS order.', processed_at = now()
    where id = event_record.id
    returning * into event_record;
    return jsonb_build_object('ignored', true, 'event', to_jsonb(event_record));
  end if;

  if order_record.status = 'paid' then
    update public.payos_webhook_events
    set status = 'processed', processed_at = now()
    where id = event_record.id
    returning * into event_record;
    return jsonb_build_object('already_processed', true, 'order', to_jsonb(order_record), 'event', to_jsonb(event_record));
  end if;

  if order_record.status <> 'pending' then
    update public.payos_webhook_events
    set status = 'ignored', error = 'PayOS order không ở trạng thái pending.', processed_at = now()
    where id = event_record.id
    returning * into event_record;
    return jsonb_build_object('ignored', true, 'order', to_jsonb(order_record), 'event', to_jsonb(event_record));
  end if;

  if order_record.amount <> amount_input then
    update public.payos_webhook_events
    set status = 'failed', error = 'Số tiền webhook không khớp PayOS order.', processed_at = now()
    where id = event_record.id;
    raise exception 'Số tiền webhook không khớp PayOS order.' using errcode = '22023';
  end if;

  if order_record.purpose = 'crm_payment' then
    rpc_result := private.confirm_crm_payment_from_payos(
      order_record.payment_id,
      'PayOS paid: ' || coalesce(nullif(trim(reference_input), ''), order_record.order_code::text)
    );
  elsif order_record.purpose = 'wallet_topup' then
    rpc_result := private.post_wallet_ledger(
      order_record.wallet_user_id,
      order_record.amount,
      'admin_adjustment',
      'payos_orders',
      order_record.id::text,
      'payos-paid:' || order_record.order_code::text,
      'Nạp xu PayOS',
      'PayOS paid: ' || coalesce(nullif(trim(reference_input), ''), order_record.order_code::text),
      jsonb_build_object(
        'source', 'payos',
        'order_code', order_record.order_code,
        'payment_link_id', coalesce(payment_link_id_input, order_record.payment_link_id)
      ),
      null,
      'system'
    );
  else
    raise exception 'Mục đích PayOS không hợp lệ.' using errcode = '22023';
  end if;

  update public.payos_orders
  set
    status = 'paid',
    payment_link_id = coalesce(nullif(trim(payment_link_id_input), ''), payment_link_id),
    provider_payload = provider_payload || coalesce(provider_payload_input, '{}'::jsonb),
    confirmed_at = now(),
    processed_at = now(),
    updated_at = now()
  where id = order_record.id
  returning * into order_record;

  update public.payos_webhook_events
  set status = 'processed', processed_at = now()
  where id = event_record.id
  returning * into event_record;

  return jsonb_build_object(
    'order', to_jsonb(order_record),
    'event', to_jsonb(event_record),
    'result', rpc_result,
    'already_processed', false
  );
end;
$function$;

revoke all on table public.payos_orders from public, anon;
revoke all on table public.payos_webhook_events from public, anon;
grant select on table public.payos_orders to authenticated;
grant select on table public.payos_webhook_events to authenticated;

revoke all on function public.record_payos_payment_link(text, bigint, uuid, bigint, numeric, text, text, text, text, jsonb) from public, anon, authenticated;
grant execute on function public.record_payos_payment_link(text, bigint, uuid, bigint, numeric, text, text, text, text, jsonb) to authenticated;

revoke all on function public.handle_payos_webhook(bigint, numeric, text, text, jsonb, text, text) from public, anon, authenticated;
grant execute on function public.handle_payos_webhook(bigint, numeric, text, text, jsonb, text, text) to service_role;
