-- Round 2: admin-managed expense categories and one filtered expense workspace.
-- Revenue continues to come from payment_business_dates.
begin;

create table if not exists public.expense_categories (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  is_salary boolean not null default false,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  archived_by uuid references auth.users(id) on delete set null,
  constraint expense_categories_code_check check (code ~ '^[a-z0-9][a-z0-9_-]{1,80}$'),
  constraint expense_categories_name_check check (length(btrim(name)) between 1 and 120)
);

insert into public.expense_categories(code,name,is_salary)
values ('salary','Lương / Nhân sự',true),('bonus','Thưởng',false),('advertising','Quảng cáo',false),
  ('infrastructure','Công cụ / Dịch vụ',false),('refund','Hoàn tiền',false),('other','Khác',false)
on conflict(code) do update set name=excluded.name,is_salary=excluded.is_salary;

alter table public.expenses add column if not exists category_id bigint references public.expense_categories(id) on delete restrict;
update public.expenses e set category_id=c.id from public.expense_categories c
where e.category_id is null and c.code=e.category;
alter table public.expenses alter column category_id set not null;
alter table public.expenses drop constraint if exists expenses_category_check;
create index if not exists expenses_category_id_date_idx on public.expenses(category_id,expense_date desc) where archived_at is null;

create or replace function private.set_expense_category_updated_at()
returns trigger language plpgsql set search_path=pg_catalog,public as $$
begin new.updated_at:=now(); return new; end;
$$;
revoke all on function private.set_expense_category_updated_at() from public;
drop trigger if exists expense_categories_set_updated_at on public.expense_categories;
create trigger expense_categories_set_updated_at before update on public.expense_categories
for each row execute function private.set_expense_category_updated_at();

alter table public.expense_categories enable row level security;
revoke all on table public.expense_categories from public,anon,authenticated;
grant select on table public.expense_categories to authenticated;
grant all on table public.expense_categories to service_role;
grant usage,select on sequence public.expense_categories_id_seq to service_role;
drop policy if exists expense_categories_permission_read on public.expense_categories;
create policy expense_categories_permission_read on public.expense_categories for select to authenticated
using ((select public.has_user_permission('expenses')));

create or replace function public.get_expenses_data(
  p_start_date date default null,p_end_date date default null,p_category text default null,
  p_employee_user_id uuid default null,p_include_archived boolean default false
) returns jsonb language plpgsql stable security definer set search_path=pg_catalog,public as $$
declare result jsonb; total_expense numeric; total_revenue numeric;
begin
  if not public.has_user_permission('expenses') then raise exception 'Không có quyền quản lý chi phí.' using errcode='42501'; end if;
  if p_start_date is not null and p_end_date is not null and p_start_date>p_end_date then raise exception 'Khoảng ngày chi phí không hợp lệ.'; end if;
  if p_category is not null and not exists(select 1 from public.expense_categories where code=p_category) then raise exception 'Danh mục chi phí không hợp lệ.'; end if;
  with filtered as materialized (
    select e.*,c.name category_name,c.is_salary category_is_salary,
      coalesce(up.display_name,up.username,'Người dùng đã xóa') employee_name,
      coalesce(creator.display_name,creator.username,'Quản trị viên') creator_name
    from public.expenses e join public.expense_categories c on c.id=e.category_id
    left join public.user_profiles up on up.user_id=e.employee_user_id
    left join public.user_profiles creator on creator.user_id=e.created_by
    where (p_include_archived or e.archived_at is null)
      and (p_start_date is null or e.expense_date>=p_start_date) and (p_end_date is null or e.expense_date<=p_end_date)
      and (p_category is null or c.code=p_category) and (p_employee_user_id is null or e.employee_user_id=p_employee_user_id)
  ) select coalesce(sum(amount),0) into total_expense from filtered;
  select coalesce(sum(p.total_amount),0) into total_revenue from public.payment_business_dates p
    where lower(p.payment_status)='completed' and p.confirmed_at is not null
      and (p_start_date is null or p.revenue_date>=p_start_date) and (p_end_date is null or p.revenue_date<=p_end_date);
  with filtered as materialized (
    select e.*,c.name category_name,c.is_salary category_is_salary,
      coalesce(up.display_name,up.username,'Người dùng đã xóa') employee_name,
      coalesce(creator.display_name,creator.username,'Quản trị viên') creator_name
    from public.expenses e join public.expense_categories c on c.id=e.category_id
    left join public.user_profiles up on up.user_id=e.employee_user_id
    left join public.user_profiles creator on creator.user_id=e.created_by
    where (p_include_archived or e.archived_at is null)
      and (p_start_date is null or e.expense_date>=p_start_date) and (p_end_date is null or e.expense_date<=p_end_date)
      and (p_category is null or c.code=p_category) and (p_employee_user_id is null or e.employee_user_id=p_employee_user_id)
  ) select jsonb_build_object(
    'rows',coalesce((select jsonb_agg(to_jsonb(f) order by f.expense_date desc,f.id desc) from filtered f),'[]'::jsonb),
    'totalAmount',total_expense,'totalExpense',total_expense,'totalRevenue',total_revenue,'netProfit',total_revenue-total_expense,
    'totalRows',(select count(*) from filtered),
    'categories',coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'code',c.code,'name',c.name,
      'isSalary',c.is_salary,'isActive',c.is_active) order by c.is_active desc,c.name) from public.expense_categories c),'[]'::jsonb),
    'employees',coalesce((select jsonb_agg(jsonb_build_object('user_id',up.user_id,'display_name',coalesce(up.display_name,up.username,'Chưa có tên'),'username',up.username)
      order by coalesce(up.display_name,up.username,'')) from public.user_profiles up where up.status='active'),'[]'::jsonb)
  ) into result;
  return result;
end;
$$;

create or replace function public.save_expense(
  p_id bigint,p_category text,p_amount numeric,p_expense_date date,p_employee_user_id uuid,
  p_salary_period date,p_payment_method text,p_note text default null
) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare actor public.user_profiles%rowtype; before_expense public.expenses%rowtype; saved_expense public.expenses%rowtype;
  selected_category public.expense_categories%rowtype; normalized_category text:=lower(btrim(coalesce(p_category,'')));
  normalized_method text:=lower(btrim(coalesce(p_payment_method,''))); normalized_note text:=nullif(btrim(coalesce(p_note,'')),'');
  normalized_period date:=case when p_salary_period is null then null else date_trunc('month',p_salary_period)::date end;
  duplicate_salary boolean:=false; employee_name text; log_action text;
begin
  if not public.has_user_permission('expenses') then raise exception 'Không có quyền quản lý chi phí.' using errcode='42501'; end if;
  select * into selected_category from public.expense_categories where code=normalized_category and is_active;
  if selected_category.id is null then raise exception 'Danh mục chi phí không hợp lệ hoặc đã lưu trữ.'; end if;
  if p_amount is null or p_amount<=0 then raise exception 'Số tiền phải lớn hơn 0.'; end if;
  if p_expense_date is null then raise exception 'Ngày chi là bắt buộc.'; end if;
  if normalized_method='' or length(normalized_method)>50 then raise exception 'Phương thức chi không hợp lệ.'; end if;
  if selected_category.is_salary and (p_employee_user_id is null or normalized_period is null) then raise exception 'Lương cần có nhân viên và kỳ lương.'; end if;
  if not selected_category.is_salary then normalized_period:=null; end if;
  if p_employee_user_id is not null and not exists(select 1 from public.user_profiles where user_id=p_employee_user_id) then raise exception 'Nhân viên không tồn tại.'; end if;
  select * into actor from public.user_profiles where user_id=auth.uid();
  if actor.user_id is null then raise exception 'Không tìm thấy tài khoản thực hiện.' using errcode='42501'; end if;
  duplicate_salary:=selected_category.is_salary and exists(select 1 from public.expenses e join public.expense_categories c on c.id=e.category_id
    where c.is_salary and e.employee_user_id=p_employee_user_id and e.salary_period=normalized_period and e.archived_at is null and (p_id is null or e.id<>p_id));
  if p_id is null then
    insert into public.expenses(category,category_id,amount,expense_date,employee_user_id,salary_period,payment_method,note,created_by)
    values(selected_category.code,selected_category.id,p_amount,p_expense_date,p_employee_user_id,normalized_period,normalized_method,normalized_note,auth.uid())
    returning * into saved_expense; log_action:=case when selected_category.is_salary then 'create_salary_expense' else 'create_expense' end;
  else
    select * into before_expense from public.expenses where id=p_id and archived_at is null for update;
    if before_expense.id is null then raise exception 'Khoản chi không tồn tại hoặc đã hủy.'; end if;
    update public.expenses set category=selected_category.code,category_id=selected_category.id,amount=p_amount,expense_date=p_expense_date,
      employee_user_id=p_employee_user_id,salary_period=normalized_period,payment_method=normalized_method,note=normalized_note
      where id=p_id returning * into saved_expense; log_action:='update_expense';
  end if;
  select coalesce(up.display_name,up.username,'Nhân viên') into employee_name from public.user_profiles up where up.user_id=saved_expense.employee_user_id;
  insert into public.audit_logs(actor_id,actor_name,actor_role,actor_type,module,entity,record_id,action,before,after,reason)
  values(auth.uid(),coalesce(actor.display_name,actor.username,'Quản trị viên'),case when actor.is_system_admin then 'system_admin' else 'staff' end,'staff',
    'Expense','expenses',saved_expense.id::text,log_action,case when before_expense.id is null then null else to_jsonb(before_expense) end,
    to_jsonb(saved_expense)||jsonb_build_object('employee_name',employee_name,'category_name',selected_category.name),
    case when selected_category.is_salary then 'Ghi nhận lương '||to_char(normalized_period,'MM/YYYY')||' cho '||coalesce(employee_name,'nhân viên')||' – '||trim(to_char(p_amount,'FM999G999G999G990'))||'đ'
      when log_action='update_expense' then 'Sửa chi phí '||trim(to_char(p_amount,'FM999G999G999G990'))||'đ – '||selected_category.name
      else 'Thêm chi phí '||trim(to_char(p_amount,'FM999G999G999G990'))||'đ – '||selected_category.name end);
  return jsonb_build_object('expense',to_jsonb(saved_expense),'duplicateSalary',duplicate_salary);
end;
$$;

create or replace function public.save_expense_category(p_id bigint,p_name text)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare saved public.expense_categories%rowtype; normalized_name text:=btrim(coalesce(p_name,'')); generated_code text;
begin
  if not public.has_user_permission('expenses') then raise exception 'Không có quyền quản lý chi phí.' using errcode='42501'; end if;
  if length(normalized_name) not between 1 and 120 then raise exception 'Tên danh mục phải có từ 1 đến 120 ký tự.'; end if;
  if exists(select 1 from public.expense_categories where lower(name)=lower(normalized_name) and (p_id is null or id<>p_id)) then raise exception 'Tên danh mục đã tồn tại.'; end if;
  if p_id is null then
    generated_code:='custom-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSUS');
    insert into public.expense_categories(code,name,created_by) values(generated_code,normalized_name,auth.uid()) returning * into saved;
  else
    update public.expense_categories set name=normalized_name where id=p_id and archived_at is null returning * into saved;
    if saved.id is null then raise exception 'Danh mục không tồn tại hoặc đã lưu trữ.'; end if;
  end if;
  return to_jsonb(saved);
end;
$$;

create or replace function public.archive_expense_category(p_id bigint)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare saved public.expense_categories%rowtype;
begin
  if not public.has_user_permission('expenses') then raise exception 'Không có quyền quản lý chi phí.' using errcode='42501'; end if;
  update public.expense_categories set is_active=false,archived_at=now(),archived_by=auth.uid()
    where id=p_id and archived_at is null returning * into saved;
  if saved.id is null then raise exception 'Danh mục không tồn tại hoặc đã lưu trữ.'; end if;
  return to_jsonb(saved);
end;
$$;

revoke all on function public.get_expenses_data(date,date,text,uuid,boolean) from public,anon;
revoke all on function public.save_expense(bigint,text,numeric,date,uuid,date,text,text) from public,anon;
revoke all on function public.save_expense_category(bigint,text) from public,anon;
revoke all on function public.archive_expense_category(bigint) from public,anon;
grant execute on function public.get_expenses_data(date,date,text,uuid,boolean) to authenticated;
grant execute on function public.save_expense(bigint,text,numeric,date,uuid,date,text,text) to authenticated;
grant execute on function public.save_expense_category(bigint,text) to authenticated;
grant execute on function public.archive_expense_category(bigint) to authenticated;

commit;
