-- Discount / Promotion Engine V1. Forward-only; no historical migration is changed.
-- VND rounding rule: percentage discounts are rounded down to the nearest integer.

create table public.promotions (
  id bigint generated by default as identity primary key,
  code text not null,
  name text not null,
  description text,
  discount_type text not null check (discount_type in ('percentage','fixed_amount','bonus_months')),
  discount_value bigint not null check (discount_value > 0),
  max_discount_amount bigint check (max_discount_amount is null or max_discount_amount > 0),
  minimum_order_amount bigint check (minimum_order_amount is null or minimum_order_amount >= 0),
  minimum_kiosk_count integer check (minimum_kiosk_count is null or minimum_kiosk_count > 0),
  minimum_months integer check (minimum_months is null or minimum_months > 0),
  starts_at timestamptz,
  ends_at timestamptz,
  usage_limit_total integer check (usage_limit_total is null or usage_limit_total > 0),
  usage_limit_per_customer integer check (usage_limit_per_customer is null or usage_limit_per_customer > 0),
  scope_type text not null default 'all' check (scope_type in ('all','category','business_type')),
  is_active boolean not null default true,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint promotions_percentage_value check (discount_type <> 'percentage' or discount_value <= 100),
  constraint promotions_max_only_percentage check (max_discount_amount is null or discount_type = 'percentage'),
  constraint promotions_valid_period check (ends_at is null or starts_at is null or ends_at >= starts_at),
  constraint promotions_code_normalized check (code = pg_catalog.upper(pg_catalog.btrim(code)) and code <> '')
);

create unique index promotions_code_ci_uidx on public.promotions (pg_catalog.upper(pg_catalog.btrim(code)));

create table public.promotion_categories (
  promotion_id bigint not null references public.promotions(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete restrict,
  primary key (promotion_id, category_id)
);

create table public.promotion_business_types (
  promotion_id bigint not null references public.promotions(id) on delete cascade,
  business_type_id bigint not null references public.business_types(id) on delete restrict,
  primary key (promotion_id, business_type_id)
);

alter table public.registration_batches
  add column promotion_id bigint references public.promotions(id) on delete restrict,
  add column promotion_code text,
  add column promotion_snapshot jsonb,
  add column subtotal_before_discount bigint,
  add column eligible_subtotal bigint,
  add column discount_amount bigint not null default 0 check (discount_amount >= 0);

alter table public.registration_batch_items
  drop constraint registration_batch_items_total_amount_check,
  add constraint registration_batch_items_total_amount_check check (total_amount >= 0),
  add column paid_months integer,
  add column bonus_months integer not null default 0 check (bonus_months >= 0),
  add column effective_service_months integer,
  add column promotion_eligible boolean not null default false;

update public.registration_batch_items
set paid_months = months, effective_service_months = months
where paid_months is null or effective_service_months is null;

alter table public.registration_batch_items
  alter column paid_months set not null,
  alter column effective_service_months set not null,
  add constraint registration_batch_items_effective_months_check
    check (effective_service_months = paid_months + bonus_months and paid_months = months);

create table public.promotion_usages (
  id bigint generated by default as identity primary key,
  promotion_id bigint not null references public.promotions(id) on delete restrict,
  customer_id bigint not null references public.customers(id) on delete restrict,
  registration_batch_id bigint not null references public.registration_batches(id) on delete restrict,
  payment_id bigint not null references public.payments(id) on delete restrict,
  code_snapshot text not null,
  discount_type_snapshot text not null check (discount_type_snapshot in ('percentage','fixed_amount','bonus_months')),
  discount_value_snapshot bigint not null,
  subtotal_before_discount bigint not null check (subtotal_before_discount > 0),
  eligible_subtotal bigint not null check (eligible_subtotal >= 0 and eligible_subtotal <= subtotal_before_discount),
  discount_amount bigint not null check (discount_amount >= 0 and discount_amount <= eligible_subtotal),
  final_amount bigint not null check (final_amount > 0),
  total_bonus_months integer not null default 0 check (total_bonus_months >= 0),
  created_at timestamptz not null default pg_catalog.now(),
  unique (registration_batch_id),
  unique (payment_id),
  check (discount_value_snapshot > 0),
  check (final_amount = subtotal_before_discount - discount_amount)
);

create index promotion_usages_promotion_idx on public.promotion_usages(promotion_id, created_at);
create index promotion_usages_customer_idx on public.promotion_usages(promotion_id, customer_id);

alter table public.promotions enable row level security;
alter table public.promotion_categories enable row level security;
alter table public.promotion_business_types enable row level security;
alter table public.promotion_usages enable row level security;

-- CRM access follows the authoritative user_profiles role, not editable user metadata.
create policy promotions_admin_all on public.promotions for all to authenticated
using (exists (select 1 from public.user_roles p where p.user_id = (select auth.uid()) and pg_catalog.lower(p.role) = 'admin' and p.is_active))
with check (exists (select 1 from public.user_roles p where p.user_id = (select auth.uid()) and pg_catalog.lower(p.role) = 'admin' and p.is_active));
create policy promotion_categories_admin_all on public.promotion_categories for all to authenticated
using (exists (select 1 from public.user_roles p where p.user_id = (select auth.uid()) and pg_catalog.lower(p.role) = 'admin' and p.is_active))
with check (exists (select 1 from public.user_roles p where p.user_id = (select auth.uid()) and pg_catalog.lower(p.role) = 'admin' and p.is_active));
create policy promotion_business_types_admin_all on public.promotion_business_types for all to authenticated
using (exists (select 1 from public.user_roles p where p.user_id = (select auth.uid()) and pg_catalog.lower(p.role) = 'admin' and p.is_active))
with check (exists (select 1 from public.user_roles p where p.user_id = (select auth.uid()) and pg_catalog.lower(p.role) = 'admin' and p.is_active));
create policy promotion_usages_admin_read on public.promotion_usages for select to authenticated
using (exists (select 1 from public.user_roles p where p.user_id = (select auth.uid()) and pg_catalog.lower(p.role) = 'admin' and p.is_active));

create or replace function private.evaluate_registration_promotion(
  promotion_code_input text,
  customer_id_input bigint,
  items_input jsonb
) returns jsonb language plpgsql security definer set search_path = '' as $function$
declare
  normalized_code text := pg_catalog.upper(pg_catalog.btrim(coalesce(promotion_code_input,'')));
  promotion_record public.promotions%rowtype;
  item jsonb;
  subtotal bigint := 0;
  eligible_total bigint := 0;
  discount_total bigint := 0;
  kiosk_count integer := 0;
  total_bonus integer := 0;
  eligible boolean;
  item_total bigint;
  item_months integer;
  evaluated_items jsonb := '[]'::jsonb;
begin
  if jsonb_typeof(items_input) <> 'array' then raise exception 'Danh sách Kiosk không hợp lệ.' using errcode='22023'; end if;
  for item in select value from jsonb_array_elements(items_input) loop
    item_total := coalesce((item->>'totalAmount')::bigint,0);
    if item_total < 0 then raise exception 'Giá trị Kiosk không hợp lệ.' using errcode='22023'; end if;
    subtotal := subtotal + item_total;
    kiosk_count := kiosk_count + 1;
  end loop;
  if normalized_code = '' then
    return jsonb_build_object('valid',true,'code',null,'subtotal',subtotal,'eligibleSubtotal',0,'discountAmount',0,'finalAmount',subtotal,'items',items_input,'message','');
  end if;
  select * into promotion_record from public.promotions where code = normalized_code;
  if not found then return jsonb_build_object('valid',false,'code',normalized_code,'message','Mã giảm giá không tồn tại.'); end if;
  if not promotion_record.is_active then return jsonb_build_object('valid',false,'code',normalized_code,'message','Mã giảm giá đang tạm ngưng.'); end if;
  if promotion_record.starts_at is not null and pg_catalog.now() < promotion_record.starts_at then return jsonb_build_object('valid',false,'code',normalized_code,'message','Mã này chưa bắt đầu.'); end if;
  if promotion_record.ends_at is not null and pg_catalog.now() > promotion_record.ends_at then return jsonb_build_object('valid',false,'code',normalized_code,'message','Mã giảm giá đã hết hạn.'); end if;
  if promotion_record.minimum_order_amount is not null and subtotal < promotion_record.minimum_order_amount then return jsonb_build_object('valid',false,'code',normalized_code,'message','Đơn hàng chưa đạt giá trị tối thiểu.'); end if;
  if promotion_record.minimum_kiosk_count is not null and kiosk_count < promotion_record.minimum_kiosk_count then return jsonb_build_object('valid',false,'code',normalized_code,'message','Mã này yêu cầu đăng ký ít nhất '||promotion_record.minimum_kiosk_count||' Kiosk.'); end if;
  if promotion_record.usage_limit_total is not null and (select count(*) from public.promotion_usages u where u.promotion_id=promotion_record.id) >= promotion_record.usage_limit_total then return jsonb_build_object('valid',false,'code',normalized_code,'message','Mã đã hết lượt sử dụng.'); end if;
  if customer_id_input is not null and promotion_record.usage_limit_per_customer is not null and (select count(*) from public.promotion_usages u where u.promotion_id=promotion_record.id and u.customer_id=customer_id_input) >= promotion_record.usage_limit_per_customer then return jsonb_build_object('valid',false,'code',normalized_code,'message','Bạn đã sử dụng hết số lượt của mã này.'); end if;

  for item in select value from jsonb_array_elements(items_input) loop
    item_total := coalesce((item->>'totalAmount')::bigint,0);
    item_months := coalesce((item->>'months')::integer,0);
    eligible := (promotion_record.minimum_months is null or item_months >= promotion_record.minimum_months)
      and (promotion_record.scope_type='all'
        or (promotion_record.scope_type='category' and exists(select 1 from public.promotion_categories s where s.promotion_id=promotion_record.id and s.category_id=(item->>'categoryId')::bigint))
        or (promotion_record.scope_type='business_type' and exists(select 1 from public.promotion_business_types s where s.promotion_id=promotion_record.id and s.business_type_id=(item->>'businessTypeId')::bigint)));
    if eligible then eligible_total := eligible_total + item_total; end if;
    evaluated_items := evaluated_items || jsonb_build_array(item || jsonb_build_object('eligible',eligible,'bonusMonths',case when eligible and promotion_record.discount_type='bonus_months' then promotion_record.discount_value else 0 end,'effectiveMonths',item_months + case when eligible and promotion_record.discount_type='bonus_months' then promotion_record.discount_value else 0 end));
    if eligible and promotion_record.discount_type='bonus_months' then total_bonus := total_bonus + promotion_record.discount_value; end if;
  end loop;
  if eligible_total = 0 then return jsonb_build_object('valid',false,'code',normalized_code,'message','Mã chỉ áp dụng cho một số ngành nghề hoặc thời hạn đăng ký.'); end if;
  if promotion_record.discount_type='percentage' then discount_total := pg_catalog.floor(eligible_total * promotion_record.discount_value / 100.0)::bigint; if promotion_record.max_discount_amount is not null then discount_total:=least(discount_total,promotion_record.max_discount_amount); end if;
  elsif promotion_record.discount_type='fixed_amount' then discount_total := least(eligible_total,promotion_record.discount_value);
  end if;
  if subtotal - discount_total <= 0 then return jsonb_build_object('valid',false,'code',normalized_code,'message','Mã làm tổng thanh toán bằng 0 và chưa được hỗ trợ.'); end if;
  return jsonb_build_object('valid',true,'code',normalized_code,'promotionId',promotion_record.id,'discountType',promotion_record.discount_type,'discountValue',promotion_record.discount_value,'subtotal',subtotal,'eligibleSubtotal',eligible_total,'discountAmount',discount_total,'finalAmount',subtotal-discount_total,'totalBonusMonths',total_bonus,'items',evaluated_items,'message','Áp dụng mã '||normalized_code||' thành công.');
end;$function$;

revoke all on function private.evaluate_registration_promotion(text,bigint,jsonb) from public, anon, authenticated;

create or replace function public.preview_registration_promotion(promotion_code_input text, phone_input text, items_input jsonb)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare customer_value bigint; normalized_phone text:=pg_catalog.regexp_replace(coalesce(phone_input,''),'[^0-9+]','','g');
begin
  select id into customer_value from public.customers where pg_catalog.regexp_replace(coalesce(phone,''),'[^0-9+]','','g')=normalized_phone order by id limit 1;
  return private.evaluate_registration_promotion(promotion_code_input,customer_value,items_input);
end;$function$;
revoke all on function public.preview_registration_promotion(text,text,jsonb) from public,anon,authenticated;
grant execute on function public.preview_registration_promotion(text,text,jsonb) to service_role;

create or replace function public.prepare_registration_batch_for_payos(request_ids_input bigint[], phone_input text, promotion_code_input text default null)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare result jsonb; batch_record public.registration_batches%rowtype; evaluation jsonb; items jsonb;
begin
  if coalesce(auth.jwt()->>'role','') <> 'service_role' then raise exception 'Chỉ API server được chuẩn bị thanh toán đăng ký.' using errcode='42501'; end if;
  result := public.prepare_registration_batch_for_payos(request_ids_input,phone_input);
  select * into batch_record from public.registration_batches where id=(result->'batch'->>'id')::bigint for update;
  if batch_record.promotion_snapshot is not null then
    if coalesce(batch_record.promotion_code,'') <> pg_catalog.upper(pg_catalog.btrim(coalesce(promotion_code_input,''))) then raise exception 'Mã ưu đãi của lô thanh toán đã được khóa.' using errcode='22023'; end if;
    return result || jsonb_build_object('promotion',batch_record.promotion_snapshot,'batch',to_jsonb(batch_record));
  end if;
  select jsonb_agg(jsonb_build_object('itemId',i.id,'kioskId',i.kiosk_id,'months',i.months,'totalAmount',i.total_amount,'businessTypeId',i.business_type_id,'categoryId',b.category_id) order by i.id)
    into items from public.registration_batch_items i join public.business_types b on b.id=i.business_type_id where i.batch_id=batch_record.id;
  evaluation := private.evaluate_registration_promotion(promotion_code_input,batch_record.customer_id,items);
  if not coalesce((evaluation->>'valid')::boolean,false) then raise exception '%', evaluation->>'message' using errcode='P0001'; end if;
  update public.registration_batches set promotion_id=nullif(evaluation->>'promotionId','')::bigint,promotion_code=evaluation->>'code',promotion_snapshot=evaluation,subtotal_before_discount=(evaluation->>'subtotal')::bigint,eligible_subtotal=(evaluation->>'eligibleSubtotal')::bigint,discount_amount=(evaluation->>'discountAmount')::bigint,total_amount=(evaluation->>'finalAmount')::bigint,updated_at=pg_catalog.now() where id=batch_record.id returning * into batch_record;
  update public.payments set price_per_month=(evaluation->>'subtotal')::bigint,discount=(evaluation->>'discountAmount')::bigint,total_amount=(evaluation->>'finalAmount')::bigint where id=batch_record.payment_id;
  update public.registration_batch_items i set promotion_eligible=coalesce((x.value->>'eligible')::boolean,false),bonus_months=coalesce((x.value->>'bonusMonths')::integer,0),effective_service_months=coalesce((x.value->>'effectiveMonths')::integer,i.months) from jsonb_array_elements(evaluation->'items') x where i.id=(x.value->>'itemId')::bigint;
  -- Allocate an order-level money discount across eligible Kiosks using exact
  -- integer VND. Floor each proportional share, then distribute the remainder
  -- one đồng at a time in stable item-id order. Net item amounts sum to payment.
  if (evaluation->>'discountAmount')::bigint > 0 then
    with eligible_items as (
      select i.id,i.total_amount,
        pg_catalog.floor((evaluation->>'discountAmount')::numeric*i.total_amount/(evaluation->>'eligibleSubtotal')::numeric)::bigint as base_discount
      from public.registration_batch_items i
      where i.batch_id=batch_record.id and i.promotion_eligible
    ), ranked as (
      select e.*,row_number() over(order by e.id) as allocation_rank,
        (evaluation->>'discountAmount')::bigint-sum(e.base_discount) over() as remainder
      from eligible_items e
    )
    update public.registration_batch_items i
    set discount=r.base_discount+case when r.allocation_rank<=r.remainder then 1 else 0 end,
        total_amount=i.total_amount-(r.base_discount+case when r.allocation_rank<=r.remainder then 1 else 0 end)
    from ranked r where i.id=r.id;
  end if;
  return result || jsonb_build_object('promotion',evaluation,'batch',to_jsonb(batch_record),'payment',(select to_jsonb(p) from public.payments p where p.id=batch_record.payment_id),'items',(select jsonb_agg(jsonb_build_object('requestId',i.registration_request_id,'kioskId',i.kiosk_id,'name',k.facebook_name,'months',i.months,'paidMonths',i.paid_months,'bonusMonths',i.bonus_months,'effectiveMonths',i.effective_service_months,'pricePerMonth',i.price_per_month,'discount',i.discount,'totalAmount',i.total_amount,'promotionEligible',i.promotion_eligible) order by i.id) from public.registration_batch_items i join public.kiosks k on k.id=i.kiosk_id where i.batch_id=batch_record.id));
end;$function$;
revoke all on function public.prepare_registration_batch_for_payos(bigint[],text,text) from public,anon,authenticated;
grant execute on function public.prepare_registration_batch_for_payos(bigint[],text,text) to service_role;

create or replace function private.finalize_registration_promotion_usage() returns trigger language plpgsql security definer set search_path='' as $function$
declare batch_record public.registration_batches%rowtype; promotion_record public.promotions%rowtype;
begin
  if new.payment_status <> 'completed' or old.payment_status = 'completed' or new.registration_batch_id is null then return new; end if;
  select * into batch_record from public.registration_batches where id=new.registration_batch_id for update;
  if batch_record.promotion_id is null then return new; end if;
  select * into promotion_record from public.promotions where id=batch_record.promotion_id for update;
  if promotion_record.usage_limit_total is not null and (select count(*) from public.promotion_usages where promotion_id=promotion_record.id) >= promotion_record.usage_limit_total then raise exception 'Mã đã hết lượt sử dụng.' using errcode='P0001'; end if;
  if promotion_record.usage_limit_per_customer is not null and (select count(*) from public.promotion_usages where promotion_id=promotion_record.id and customer_id=batch_record.customer_id) >= promotion_record.usage_limit_per_customer then raise exception 'Khách hàng đã hết lượt sử dụng mã.' using errcode='P0001'; end if;
  insert into public.promotion_usages(promotion_id,customer_id,registration_batch_id,payment_id,code_snapshot,discount_type_snapshot,discount_value_snapshot,subtotal_before_discount,eligible_subtotal,discount_amount,final_amount,total_bonus_months)
  values(promotion_record.id,batch_record.customer_id,batch_record.id,new.id,batch_record.promotion_code,batch_record.promotion_snapshot->>'discountType',(batch_record.promotion_snapshot->>'discountValue')::bigint,batch_record.subtotal_before_discount,batch_record.eligible_subtotal,batch_record.discount_amount,batch_record.total_amount,coalesce((batch_record.promotion_snapshot->>'totalBonusMonths')::integer,0)) on conflict (registration_batch_id) do nothing;
  return new;
end;$function$;
revoke all on function private.finalize_registration_promotion_usage() from public,anon,authenticated;
create trigger finalize_registration_promotion_usage_trigger after update of payment_status on public.payments for each row execute function private.finalize_registration_promotion_usage();

create or replace function private.protect_completed_batch_promotion_snapshot() returns trigger language plpgsql set search_path='' as $function$
begin
  if exists(select 1 from public.payments p where p.registration_batch_id=old.id and p.payment_status='completed') then
    raise exception 'Không thể thay đổi ảnh chụp ưu đãi của thanh toán đã hoàn tất.' using errcode='23514';
  end if;
  return new;
end;$function$;
revoke all on function private.protect_completed_batch_promotion_snapshot() from public,anon,authenticated;
create trigger protect_completed_batch_promotion_snapshot_trigger
before update of promotion_id,promotion_code,promotion_snapshot,subtotal_before_discount,eligible_subtotal,discount_amount,total_amount
on public.registration_batches for each row
execute function private.protect_completed_batch_promotion_snapshot();

-- Use the snapshotted effective duration during the existing webhook finalization.
do $migration$
declare definition text;
begin
  definition:=pg_catalog.pg_get_functiondef('private.confirm_registration_batch_from_payos(bigint,text)'::regprocedure);
  definition:=pg_catalog.replace(definition,'pg_catalog.make_interval(months=>item_record.months)','pg_catalog.make_interval(months=>item_record.effective_service_months)');
  if definition not like '%item_record.effective_service_months%' then raise exception 'Could not patch registration batch effective months.'; end if;
  execute definition;
end;$migration$;

create or replace function private.normalize_promotion_code() returns trigger language plpgsql set search_path='' as $function$
begin new.code:=pg_catalog.upper(pg_catalog.btrim(new.code)); new.updated_at:=pg_catalog.now(); return new; end;$function$;
create trigger normalize_promotion_code_trigger before insert or update on public.promotions for each row execute function private.normalize_promotion_code();

create or replace function private.audit_promotion_change() returns trigger language plpgsql security definer set search_path='' as $function$
declare action_value text;
begin
  action_value:=case when tg_op='INSERT' then 'create_promotion' when old.is_active and not new.is_active then 'pause_promotion' when not old.is_active and new.is_active then 'reactivate_promotion' else 'update_promotion' end;
  perform private.write_ttc_audit('Promotion',action_value,'promotions',new.id::text,case when tg_op='UPDATE' then to_jsonb(old) else null end,to_jsonb(new),case action_value when 'create_promotion' then 'Created promotion' when 'pause_promotion' then 'Paused promotion' when 'reactivate_promotion' then 'Reactivated promotion' else 'Updated promotion' end);
  return new;
end;$function$;
revoke all on function private.audit_promotion_change() from public,anon,authenticated;
create trigger audit_promotion_change_trigger after insert or update on public.promotions for each row execute function private.audit_promotion_change();

revoke all on table public.promotions,public.promotion_categories,public.promotion_business_types,public.promotion_usages from public;
revoke all on table public.promotions,public.promotion_categories,public.promotion_business_types,public.promotion_usages from anon;
grant select on public.promotions,public.promotion_categories,public.promotion_business_types to authenticated;
grant update(is_active) on public.promotions to authenticated;
grant select on public.promotion_usages to authenticated;
revoke all on sequence public.promotions_id_seq,public.promotion_usages_id_seq from public,anon,authenticated;

create or replace function public.admin_save_promotion(promotion_id_input bigint,promotion_input jsonb,category_ids_input bigint[] default '{}'::bigint[],business_type_ids_input bigint[] default '{}'::bigint[])
returns jsonb language plpgsql security definer set search_path='' as $function$
declare saved public.promotions%rowtype; scope_value text:=coalesce(promotion_input->>'scope_type','all');
begin
  if not exists(select 1 from public.user_roles r where r.user_id=(select auth.uid()) and pg_catalog.lower(r.role)='admin' and r.is_active) then raise exception 'Bạn không có quyền quản lý mã giảm giá.' using errcode='42501'; end if;
  if scope_value='category' and coalesce(pg_catalog.array_length(category_ids_input,1),0)=0 then raise exception 'Vui lòng chọn ít nhất một danh mục.' using errcode='22023'; end if;
  if scope_value='business_type' and coalesce(pg_catalog.array_length(business_type_ids_input,1),0)=0 then raise exception 'Vui lòng chọn ít nhất một loại hình kinh doanh.' using errcode='22023'; end if;
  if scope_value='category' and exists(select 1 from pg_catalog.unnest(category_ids_input) id left join public.categories c on c.id=id where c.id is null) then raise exception 'Danh mục áp dụng không hợp lệ.' using errcode='22023'; end if;
  if scope_value='business_type' and exists(select 1 from pg_catalog.unnest(business_type_ids_input) id left join public.business_types b on b.id=id where b.id is null) then raise exception 'Loại hình kinh doanh áp dụng không hợp lệ.' using errcode='22023'; end if;
  if promotion_id_input is null then
    insert into public.promotions(code,name,description,discount_type,discount_value,max_discount_amount,minimum_order_amount,minimum_kiosk_count,minimum_months,starts_at,ends_at,usage_limit_total,usage_limit_per_customer,scope_type,is_active,created_by)
    values(promotion_input->>'code',promotion_input->>'name',promotion_input->>'description',promotion_input->>'discount_type',(promotion_input->>'discount_value')::bigint,nullif(promotion_input->>'max_discount_amount','')::bigint,nullif(promotion_input->>'minimum_order_amount','')::bigint,nullif(promotion_input->>'minimum_kiosk_count','')::integer,nullif(promotion_input->>'minimum_months','')::integer,nullif(promotion_input->>'starts_at','')::timestamptz,nullif(promotion_input->>'ends_at','')::timestamptz,nullif(promotion_input->>'usage_limit_total','')::integer,nullif(promotion_input->>'usage_limit_per_customer','')::integer,scope_value,coalesce((promotion_input->>'is_active')::boolean,true),(select auth.uid())) returning * into saved;
  else
    update public.promotions set name=promotion_input->>'name',description=promotion_input->>'description',discount_type=promotion_input->>'discount_type',discount_value=(promotion_input->>'discount_value')::bigint,max_discount_amount=nullif(promotion_input->>'max_discount_amount','')::bigint,minimum_order_amount=nullif(promotion_input->>'minimum_order_amount','')::bigint,minimum_kiosk_count=nullif(promotion_input->>'minimum_kiosk_count','')::integer,minimum_months=nullif(promotion_input->>'minimum_months','')::integer,starts_at=nullif(promotion_input->>'starts_at','')::timestamptz,ends_at=nullif(promotion_input->>'ends_at','')::timestamptz,usage_limit_total=nullif(promotion_input->>'usage_limit_total','')::integer,usage_limit_per_customer=nullif(promotion_input->>'usage_limit_per_customer','')::integer,scope_type=scope_value where id=promotion_id_input returning * into saved;
    if not found then raise exception 'Không tìm thấy chương trình khuyến mãi.' using errcode='P0002'; end if;
  end if;
  delete from public.promotion_categories where promotion_id=saved.id;
  delete from public.promotion_business_types where promotion_id=saved.id;
  if scope_value='category' then insert into public.promotion_categories(promotion_id,category_id) select saved.id,id from (select distinct pg_catalog.unnest(category_ids_input) id) selected; end if;
  if scope_value='business_type' then insert into public.promotion_business_types(promotion_id,business_type_id) select saved.id,id from (select distinct pg_catalog.unnest(business_type_ids_input) id) selected; end if;
  return to_jsonb(saved);
end;$function$;
revoke all on function public.admin_save_promotion(bigint,jsonb,bigint[],bigint[]) from public,anon,authenticated;
grant execute on function public.admin_save_promotion(bigint,jsonb,bigint[],bigint[]) to authenticated;
