-- Minimal, permission-backed content source for the public community homepage.
-- Public callers can only use the read RPC; Admin mutations are explicit RPCs.
begin;
insert into public.app_permissions(permission, display_name, sort_order, is_active)
values ('homepage-content', 'Nội dung trang chủ', 205, true)
on conflict (permission) do update
set display_name = excluded.display_name,
    sort_order = excluded.sort_order,
    is_active = true;
create table if not exists public.homepage_content (
  id smallint primary key default 1,
  hero_title text not null,
  hero_subtitle text not null,
  hero_image_url text,
  hero_group_cta_label text not null,
  hero_group_cta_url text not null,
  hero_kiosk_cta_label text not null,
  hero_kiosk_cta_route text not null default '#/register',
  posting_rules text not null,
  zalo_contacts jsonb not null default '[]'::jsonb,
  hotline_label text not null,
  hotline_number text not null,
  fanpage_label text not null default 'Fanpage Admin',
  fanpage_url text not null,
  community_links jsonb not null default '[]'::jsonb,
  section_visibility jsonb not null default '{}'::jsonb,
  section_order text[] not null default array['featured_businesses','kiosk_services','posting_rules','community_links','contact']::text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  constraint homepage_content_singleton_check check (id = 1),
  constraint homepage_content_zalo_array_check check (jsonb_typeof(zalo_contacts) = 'array'),
  constraint homepage_content_links_array_check check (jsonb_typeof(community_links) = 'array'),
  constraint homepage_content_visibility_object_check check (jsonb_typeof(section_visibility) = 'object'),
  constraint homepage_content_kiosk_route_check check (hero_kiosk_cta_route ~ '^#/[a-z0-9-]+$')
);
create table if not exists public.featured_businesses (
  id bigint generated by default as identity primary key,
  name text not null,
  image_url text,
  category text not null,
  short_description text,
  address text,
  facebook_url text,
  zalo_contact text,
  phone text,
  badge text,
  enabled boolean not null default true,
  display_order integer not null default 0,
  visibility_start timestamptz,
  visibility_end timestamptz,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  archived_by uuid references auth.users(id) on delete set null,
  constraint featured_business_name_check check (length(btrim(name)) between 1 and 160),
  constraint featured_business_category_check check (length(btrim(category)) between 1 and 100),
  constraint featured_business_description_check check (short_description is null or length(short_description) <= 500),
  constraint featured_business_badge_check check (badge is null or length(badge) <= 50),
  constraint featured_business_display_order_check check (display_order between 0 and 100000),
  constraint featured_business_visibility_check check (visibility_start is null or visibility_end is null or visibility_start <= visibility_end)
);
create index if not exists featured_business_public_order_idx
  on public.featured_businesses(display_order, id) where archived_at is null and enabled;
create or replace function private.set_homepage_updated_at()
returns trigger language plpgsql set search_path = pg_catalog, public as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
revoke all on function private.set_homepage_updated_at() from public;
drop trigger if exists homepage_content_set_updated_at on public.homepage_content;
create trigger homepage_content_set_updated_at before update on public.homepage_content
for each row execute function private.set_homepage_updated_at();
drop trigger if exists featured_businesses_set_updated_at on public.featured_businesses;
create trigger featured_businesses_set_updated_at before update on public.featured_businesses
for each row execute function private.set_homepage_updated_at();
alter table public.homepage_content enable row level security;
alter table public.featured_businesses enable row level security;
revoke all on table public.homepage_content from public, anon, authenticated;
revoke all on table public.featured_businesses from public, anon, authenticated;
grant select on table public.homepage_content, public.featured_businesses to authenticated;
grant all on table public.homepage_content, public.featured_businesses to service_role;
grant usage, select on sequence public.featured_businesses_id_seq to service_role;
drop policy if exists homepage_content_admin_read on public.homepage_content;
create policy homepage_content_admin_read on public.homepage_content for select to authenticated
using ((select public.has_user_permission('homepage-content')));
drop policy if exists featured_businesses_admin_read on public.featured_businesses;
create policy featured_businesses_admin_read on public.featured_businesses for select to authenticated
using ((select public.has_user_permission('homepage-content')));
insert into public.homepage_content (
  id, hero_title, hero_subtitle, hero_image_url,
  hero_group_cta_label, hero_group_cta_url, hero_kiosk_cta_label, hero_kiosk_cta_route,
  posting_rules, zalo_contacts, hotline_label, hotline_number, fanpage_label, fanpage_url,
  community_links, section_visibility, section_order
) values (
  1,
  'Diễn Châu – À Đây Rồi',
  'Cộng đồng kết nối người dân, cửa hàng và dịch vụ tại Diễn Châu.',
  '/images/cover.PNG',
  'Tham gia Group',
  'https://www.facebook.com/groups/1145443782801316',
  'Đăng ký Kiosk',
  '#/register',
  E'Chia sẻ thông tin rõ ràng, đúng nội dung và tôn trọng thành viên.\nKhông đăng nội dung lừa đảo, sai sự thật hoặc gây ảnh hưởng đến cộng đồng.\nLiên hệ Ban quản trị khi cần hỗ trợ duyệt bài.',
  '[{"label":"0888 680 346","url":"https://zalo.me/0888680346"},{"label":"0888 640 346","url":"https://zalo.me/0888640346"}]'::jsonb,
  '0333 015 337',
  '0333015337',
  'Fanpage Admin',
  'https://www.facebook.com/admin.dc.adayroi/',
  '[{"key":"primary","name":"Group chính","url":"https://www.facebook.com/groups/1145443782801316","enabled":true,"display_order":10},{"key":"community","name":"Group cộng đồng","url":"https://www.facebook.com/groups/dienchaugroup888","enabled":true,"display_order":20},{"key":"recruitment","name":"Group tuyển dụng","url":"https://www.facebook.com/groups/320237372898775","enabled":true,"display_order":30},{"key":"fanpage","name":"Fanpage Admin","url":"https://www.facebook.com/admin.dc.adayroi/","enabled":true,"display_order":40}]'::jsonb,
  '{"featured_businesses":true,"kiosk_services":true,"posting_rules":true,"community_links":true,"contact":true}'::jsonb,
  array['featured_businesses','kiosk_services','posting_rules','community_links','contact']::text[]
)
on conflict (id) do nothing;
create or replace function public.get_public_homepage_content()
returns jsonb language sql stable security definer set search_path = pg_catalog, public as $$
  select jsonb_build_object(
    'content', jsonb_build_object(
      'heroTitle', h.hero_title,
      'heroSubtitle', h.hero_subtitle,
      'heroImageUrl', h.hero_image_url,
      'heroGroupCtaLabel', h.hero_group_cta_label,
      'heroGroupCtaUrl', h.hero_group_cta_url,
      'heroKioskCtaLabel', h.hero_kiosk_cta_label,
      'heroKioskCtaRoute', h.hero_kiosk_cta_route,
      'postingRules', h.posting_rules,
      'zaloContacts', coalesce((select jsonb_agg(jsonb_build_object(
        'label', item->>'label', 'url', item->>'url'
      )) from jsonb_array_elements(h.zalo_contacts) item), '[]'::jsonb),
      'hotlineLabel', h.hotline_label,
      'hotlineNumber', h.hotline_number,
      'fanpageLabel', h.fanpage_label,
      'fanpageUrl', h.fanpage_url,
      'communityLinks', coalesce((select jsonb_agg(jsonb_build_object(
        'key', item->>'key', 'name', item->>'name', 'url', item->>'url',
        'enabled', case lower(coalesce(item->>'enabled', 'true')) when 'false' then false else true end,
        'display_order', case when coalesce(item->>'display_order', '') ~ '^[0-9]+$' then (item->>'display_order')::integer else 0 end
      ) order by case when coalesce(item->>'display_order', '') ~ '^[0-9]+$' then (item->>'display_order')::integer else 0 end)
      from jsonb_array_elements(h.community_links) item), '[]'::jsonb),
      'sectionVisibility', h.section_visibility,
      'sectionOrder', to_jsonb(h.section_order)
    ),
    'featuredBusinesses', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', b.id, 'name', b.name, 'imageUrl', b.image_url, 'category', b.category,
        'shortDescription', b.short_description, 'address', b.address,
        'facebookUrl', b.facebook_url, 'zaloContact', b.zalo_contact, 'phone', b.phone,
        'badge', b.badge, 'displayOrder', b.display_order
      ) order by b.display_order, b.id)
      from public.featured_businesses b
      where b.archived_at is null and b.enabled
        and (b.visibility_start is null or b.visibility_start <= now())
        and (b.visibility_end is null or b.visibility_end >= now())
    ), '[]'::jsonb)
  )
  from public.homepage_content h where h.id = 1;
$$;
create or replace function public.get_homepage_admin_data()
returns jsonb language plpgsql stable security definer set search_path = pg_catalog, public as $$
begin
  if not public.has_user_permission('homepage-content') then
    raise exception 'Không có quyền quản lý nội dung trang chủ.' using errcode = '42501';
  end if;
  return jsonb_build_object(
    'content', (select to_jsonb(h) from public.homepage_content h where h.id = 1),
    'featuredBusinesses', coalesce((select jsonb_agg(to_jsonb(b) order by b.display_order, b.id)
      from public.featured_businesses b where b.archived_at is null), '[]'::jsonb)
  );
end;
$$;
create or replace function public.save_homepage_content(p_content jsonb)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public as $$
declare
  actor public.user_profiles%rowtype;
  before_content public.homepage_content%rowtype;
  saved_content public.homepage_content%rowtype;
  links jsonb := coalesce(p_content->'communityLinks', '[]'::jsonb);
  zalo jsonb := coalesce(p_content->'zaloContacts', '[]'::jsonb);
  visibility jsonb := coalesce(p_content->'sectionVisibility', '{}'::jsonb);
  normalized_section_order text[];
begin
  if not public.has_user_permission('homepage-content') then
    raise exception 'Không có quyền quản lý nội dung trang chủ.' using errcode = '42501';
  end if;
  if jsonb_typeof(links) <> 'array' or jsonb_array_length(links) > 12 then raise exception 'Danh sách liên kết không hợp lệ.'; end if;
  if jsonb_typeof(zalo) <> 'array' or jsonb_array_length(zalo) > 5 then raise exception 'Danh sách Zalo không hợp lệ.'; end if;
  if jsonb_typeof(visibility) <> 'object' then raise exception 'Cấu hình hiển thị không hợp lệ.'; end if;
  select coalesce(array_agg(value), array[]::text[]) into normalized_section_order
  from jsonb_array_elements_text(coalesce(p_content->'sectionOrder', '[]'::jsonb));
  if cardinality(normalized_section_order) <> 5 or normalized_section_order @> array['featured_businesses','kiosk_services','posting_rules','community_links','contact']::text[] is false then
    raise exception 'Thứ tự section không hợp lệ.';
  end if;
  if nullif(btrim(p_content->>'heroTitle'), '') is null or nullif(btrim(p_content->>'heroSubtitle'), '') is null then
    raise exception 'Tiêu đề và mô tả Hero là bắt buộc.';
  end if;
  if coalesce(p_content->>'heroKioskCtaRoute', '') !~ '^#/[a-z0-9-]+$' then raise exception 'Route CTA Kiosk không hợp lệ.'; end if;

  select * into actor from public.user_profiles where user_id = auth.uid();
  select * into before_content from public.homepage_content where id = 1 for update;
  update public.homepage_content set
    hero_title = left(btrim(p_content->>'heroTitle'), 180),
    hero_subtitle = left(btrim(p_content->>'heroSubtitle'), 600),
    hero_image_url = nullif(btrim(p_content->>'heroImageUrl'), ''),
    hero_group_cta_label = left(btrim(p_content->>'heroGroupCtaLabel'), 80),
    hero_group_cta_url = btrim(p_content->>'heroGroupCtaUrl'),
    hero_kiosk_cta_label = left(btrim(p_content->>'heroKioskCtaLabel'), 80),
    hero_kiosk_cta_route = btrim(p_content->>'heroKioskCtaRoute'),
    posting_rules = left(coalesce(p_content->>'postingRules', ''), 5000),
    zalo_contacts = zalo,
    hotline_label = left(btrim(p_content->>'hotlineLabel'), 60),
    hotline_number = left(regexp_replace(coalesce(p_content->>'hotlineNumber',''), '[^0-9+]', '', 'g'), 20),
    fanpage_label = left(btrim(p_content->>'fanpageLabel'), 80),
    fanpage_url = btrim(p_content->>'fanpageUrl'),
    community_links = links,
    section_visibility = visibility,
    section_order = normalized_section_order,
    updated_by = auth.uid()
  where id = 1 returning * into saved_content;
  insert into public.audit_logs(actor_id, actor_name, actor_role, actor_type, module, entity, record_id, action, before, after, reason)
  values (auth.uid(), coalesce(actor.display_name, actor.username, 'Quản trị viên'),
    case when actor.is_system_admin then 'system_admin' else 'staff' end, 'staff',
    'Homepage', 'homepage_content', '1', 'update_homepage_content',
    to_jsonb(before_content), to_jsonb(saved_content), 'Cập nhật nội dung trang chủ');
  return to_jsonb(saved_content);
end;
$$;
create or replace function public.save_featured_business(p_business jsonb)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public as $$
declare
  actor public.user_profiles%rowtype;
  before_business public.featured_businesses%rowtype;
  saved_business public.featured_businesses%rowtype;
  business_id bigint := nullif(p_business->>'id', '')::bigint;
  start_at timestamptz := nullif(p_business->>'visibilityStart', '')::timestamptz;
  end_at timestamptz := nullif(p_business->>'visibilityEnd', '')::timestamptz;
  action_name text;
begin
  if not public.has_user_permission('homepage-content') then
    raise exception 'Không có quyền quản lý nội dung trang chủ.' using errcode = '42501';
  end if;
  if nullif(btrim(p_business->>'name'), '') is null or nullif(btrim(p_business->>'category'), '') is null then
    raise exception 'Tên và danh mục doanh nghiệp là bắt buộc.';
  end if;
  if start_at is not null and end_at is not null and start_at > end_at then raise exception 'Khoảng hiển thị không hợp lệ.'; end if;
  select * into actor from public.user_profiles where user_id = auth.uid();
  if business_id is null then
    insert into public.featured_businesses(name,image_url,category,short_description,address,facebook_url,zalo_contact,phone,badge,enabled,display_order,visibility_start,visibility_end,created_by)
    values (left(btrim(p_business->>'name'),160),nullif(btrim(p_business->>'imageUrl'),''),left(btrim(p_business->>'category'),100),
      nullif(left(btrim(p_business->>'shortDescription'),500),''),nullif(btrim(p_business->>'address'),''),nullif(btrim(p_business->>'facebookUrl'),''),
      nullif(btrim(p_business->>'zaloContact'),''),nullif(btrim(p_business->>'phone'),''),nullif(left(btrim(p_business->>'badge'),50),''),
      coalesce((p_business->>'enabled')::boolean,true),greatest(coalesce((p_business->>'displayOrder')::integer,0),0),start_at,end_at,auth.uid())
    returning * into saved_business;
    action_name := 'create_featured_business';
  else
    select * into before_business from public.featured_businesses where id = business_id and archived_at is null for update;
    if before_business.id is null then raise exception 'Doanh nghiệp không tồn tại hoặc đã lưu trữ.'; end if;
    update public.featured_businesses set
      name=left(btrim(p_business->>'name'),160), image_url=nullif(btrim(p_business->>'imageUrl'),''), category=left(btrim(p_business->>'category'),100),
      short_description=nullif(left(btrim(p_business->>'shortDescription'),500),''), address=nullif(btrim(p_business->>'address'),''),
      facebook_url=nullif(btrim(p_business->>'facebookUrl'),''), zalo_contact=nullif(btrim(p_business->>'zaloContact'),''), phone=nullif(btrim(p_business->>'phone'),''),
      badge=nullif(left(btrim(p_business->>'badge'),50),''), enabled=coalesce((p_business->>'enabled')::boolean,true),
      display_order=greatest(coalesce((p_business->>'displayOrder')::integer,0),0), visibility_start=start_at, visibility_end=end_at
    where id=business_id returning * into saved_business;
    action_name := 'update_featured_business';
  end if;
  insert into public.audit_logs(actor_id,actor_name,actor_role,actor_type,module,entity,record_id,action,before,after,reason)
  values (auth.uid(),coalesce(actor.display_name,actor.username,'Quản trị viên'),case when actor.is_system_admin then 'system_admin' else 'staff' end,'staff',
    'Homepage','featured_businesses',saved_business.id::text,action_name,case when before_business.id is null then null else to_jsonb(before_business) end,to_jsonb(saved_business),saved_business.name);
  return to_jsonb(saved_business);
end;
$$;
create or replace function public.archive_featured_business(p_id bigint)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public as $$
declare
  actor public.user_profiles%rowtype;
  before_business public.featured_businesses%rowtype;
  saved_business public.featured_businesses%rowtype;
begin
  if not public.has_user_permission('homepage-content') then raise exception 'Không có quyền quản lý nội dung trang chủ.' using errcode='42501'; end if;
  select * into actor from public.user_profiles where user_id=auth.uid();
  select * into before_business from public.featured_businesses where id=p_id and archived_at is null for update;
  if before_business.id is null then raise exception 'Doanh nghiệp không tồn tại hoặc đã lưu trữ.'; end if;
  update public.featured_businesses set archived_at=now(), archived_by=auth.uid() where id=p_id returning * into saved_business;
  insert into public.audit_logs(actor_id,actor_name,actor_role,actor_type,module,entity,record_id,action,before,after,reason)
  values (auth.uid(),coalesce(actor.display_name,actor.username,'Quản trị viên'),case when actor.is_system_admin then 'system_admin' else 'staff' end,'staff',
    'Homepage','featured_businesses',saved_business.id::text,'archive_featured_business',to_jsonb(before_business),to_jsonb(saved_business),saved_business.name);
  return to_jsonb(saved_business);
end;
$$;
revoke all on function public.get_public_homepage_content() from public, authenticated;
grant execute on function public.get_public_homepage_content() to anon, authenticated;
revoke all on function public.get_homepage_admin_data() from public, anon;
revoke all on function public.save_homepage_content(jsonb) from public, anon;
revoke all on function public.save_featured_business(jsonb) from public, anon;
revoke all on function public.archive_featured_business(bigint) from public, anon;
grant execute on function public.get_homepage_admin_data() to authenticated;
grant execute on function public.save_homepage_content(jsonb) to authenticated;
grant execute on function public.save_featured_business(jsonb) to authenticated;
grant execute on function public.archive_featured_business(bigint) to authenticated;
commit;
