-- Minimal Admin expense ledger. Apply manually after QA; this migration does not
-- modify payments or the revenue source of truth.
begin;
insert into public.app_permissions(permission, display_name, sort_order, is_active)
values ('expenses', 'Quản lý chi phí', 65, true)
on conflict (permission) do update
set display_name = excluded.display_name,
    sort_order = excluded.sort_order,
    is_active = true;
create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  category text not null,
  amount numeric(14,2) not null,
  expense_date date not null,
  employee_user_id uuid references public.user_profiles(user_id) on delete set null,
  salary_period date,
  payment_method text not null,
  note text,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  archived_by uuid references auth.users(id) on delete set null,
  constraint expenses_category_check check (category = any (array[
    'salary', 'bonus', 'advertising', 'infrastructure', 'refund', 'other'
  ]::text[])),
  constraint expenses_amount_positive_check check (amount > 0),
  constraint expenses_payment_method_check check (length(btrim(payment_method)) between 1 and 50),
  constraint expenses_salary_fields_check check (
    (category = 'salary' and employee_user_id is not null and salary_period is not null and extract(day from salary_period) = 1)
    or (category <> 'salary' and salary_period is null)
  )
);
create index if not exists expenses_active_date_idx
  on public.expenses(expense_date desc, id desc) where archived_at is null;
create index if not exists expenses_category_date_idx
  on public.expenses(category, expense_date desc) where archived_at is null;
create index if not exists expenses_salary_lookup_idx
  on public.expenses(employee_user_id, salary_period) where category = 'salary' and archived_at is null;
comment on table public.expenses is
  'Administrative expense source of truth, separate from Kiosk revenue payments.';
comment on column public.expenses.salary_period is
  'First day of the represented salary month; required only for salary expenses.';
create or replace function private.set_expense_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
revoke all on function private.set_expense_updated_at() from public;
drop trigger if exists expenses_set_updated_at on public.expenses;
create trigger expenses_set_updated_at
before update on public.expenses
for each row execute function private.set_expense_updated_at();
alter table public.expenses enable row level security;
revoke all on table public.expenses from public, anon, authenticated;
grant select on table public.expenses to authenticated;
grant all on table public.expenses to service_role;
grant usage, select on sequence public.expenses_id_seq to service_role;
drop policy if exists expenses_permission_read on public.expenses;
create policy expenses_permission_read
on public.expenses for select to authenticated
using ((select public.has_user_permission('expenses')));
create or replace function public.get_expenses_data(
  p_start_date date default null,
  p_end_date date default null,
  p_category text default null,
  p_employee_user_id uuid default null,
  p_include_archived boolean default false
)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  result jsonb;
begin
  if not public.has_user_permission('expenses') then
    raise exception 'Không có quyền quản lý chi phí.' using errcode = '42501';
  end if;
  if p_start_date is not null and p_end_date is not null and p_start_date > p_end_date then
    raise exception 'Khoảng ngày chi phí không hợp lệ.';
  end if;
  if p_category is not null and p_category <> all (array['salary','bonus','advertising','infrastructure','refund','other']::text[]) then
    raise exception 'Danh mục chi phí không hợp lệ.';
  end if;

  with filtered as materialized (
    select e.*, coalesce(up.display_name, up.username, 'Người dùng đã xóa') as employee_name,
      coalesce(creator.display_name, creator.username, 'Quản trị viên') as creator_name
    from public.expenses e
    left join public.user_profiles up on up.user_id = e.employee_user_id
    left join public.user_profiles creator on creator.user_id = e.created_by
    where (p_include_archived or e.archived_at is null)
      and (p_start_date is null or e.expense_date >= p_start_date)
      and (p_end_date is null or e.expense_date <= p_end_date)
      and (p_category is null or e.category = p_category)
      and (p_employee_user_id is null or e.employee_user_id = p_employee_user_id)
  )
  select jsonb_build_object(
    'rows', coalesce((select jsonb_agg(to_jsonb(f) order by f.expense_date desc, f.id desc) from filtered f), '[]'::jsonb),
    'totalAmount', coalesce((select sum(f.amount) from filtered f), 0),
    'totalRows', (select count(*) from filtered),
    'employees', coalesce((
      select jsonb_agg(jsonb_build_object(
        'user_id', up.user_id,
        'display_name', coalesce(up.display_name, up.username, 'Chưa có tên'),
        'username', up.username
      ) order by coalesce(up.display_name, up.username, ''))
      from public.user_profiles up
      where up.status = 'active'
    ), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;
create or replace function public.check_duplicate_salary_expense(
  p_employee_user_id uuid,
  p_salary_period date,
  p_exclude_id bigint default null
)
returns boolean
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
begin
  if not public.has_user_permission('expenses') then
    raise exception 'Không có quyền quản lý chi phí.' using errcode = '42501';
  end if;
  if p_employee_user_id is null or p_salary_period is null then return false; end if;
  return exists (
    select 1 from public.expenses e
    where e.category = 'salary'
      and e.employee_user_id = p_employee_user_id
      and e.salary_period = date_trunc('month', p_salary_period)::date
      and e.archived_at is null
      and (p_exclude_id is null or e.id <> p_exclude_id)
  );
end;
$$;
create or replace function public.save_expense(
  p_id bigint,
  p_category text,
  p_amount numeric,
  p_expense_date date,
  p_employee_user_id uuid,
  p_salary_period date,
  p_payment_method text,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  actor public.user_profiles%rowtype;
  before_expense public.expenses%rowtype;
  saved_expense public.expenses%rowtype;
  normalized_category text := lower(btrim(coalesce(p_category, '')));
  normalized_method text := lower(btrim(coalesce(p_payment_method, '')));
  normalized_note text := nullif(btrim(coalesce(p_note, '')), '');
  normalized_period date := case when p_salary_period is null then null else date_trunc('month', p_salary_period)::date end;
  duplicate_salary boolean := false;
  employee_name text;
  log_action text;
begin
  if not public.has_user_permission('expenses') then
    raise exception 'Không có quyền quản lý chi phí.' using errcode = '42501';
  end if;
  if normalized_category <> all (array['salary','bonus','advertising','infrastructure','refund','other']::text[]) then
    raise exception 'Danh mục chi phí không hợp lệ.';
  end if;
  if p_amount is null or p_amount <= 0 then raise exception 'Số tiền phải lớn hơn 0.'; end if;
  if p_expense_date is null then raise exception 'Ngày chi là bắt buộc.'; end if;
  if normalized_method = '' or length(normalized_method) > 50 then raise exception 'Phương thức chi không hợp lệ.'; end if;
  if normalized_category = 'salary' and (p_employee_user_id is null or normalized_period is null) then
    raise exception 'Lương cần có nhân viên và kỳ lương.';
  end if;
  if normalized_category <> 'salary' then normalized_period := null; end if;
  if p_employee_user_id is not null and not exists (select 1 from public.user_profiles where user_id = p_employee_user_id) then
    raise exception 'Nhân viên không tồn tại.';
  end if;

  select * into actor from public.user_profiles where user_id = auth.uid();
  if actor.user_id is null then raise exception 'Không tìm thấy tài khoản thực hiện.' using errcode = '42501'; end if;
  duplicate_salary := normalized_category = 'salary' and exists (
    select 1 from public.expenses e
    where e.category = 'salary' and e.employee_user_id = p_employee_user_id
      and e.salary_period = normalized_period and e.archived_at is null
      and (p_id is null or e.id <> p_id)
  );

  if p_id is null then
    insert into public.expenses(category, amount, expense_date, employee_user_id, salary_period, payment_method, note, created_by)
    values (normalized_category, p_amount, p_expense_date, p_employee_user_id, normalized_period, normalized_method, normalized_note, auth.uid())
    returning * into saved_expense;
    log_action := case when normalized_category = 'salary' then 'create_salary_expense' else 'create_expense' end;
  else
    select * into before_expense from public.expenses where id = p_id and archived_at is null for update;
    if before_expense.id is null then raise exception 'Khoản chi không tồn tại hoặc đã hủy.'; end if;
    update public.expenses set
      category = normalized_category,
      amount = p_amount,
      expense_date = p_expense_date,
      employee_user_id = p_employee_user_id,
      salary_period = normalized_period,
      payment_method = normalized_method,
      note = normalized_note
    where id = p_id returning * into saved_expense;
    log_action := 'update_expense';
  end if;

  select coalesce(up.display_name, up.username, 'Nhân viên') into employee_name
  from public.user_profiles up where up.user_id = saved_expense.employee_user_id;
  insert into public.audit_logs(actor_id, actor_name, actor_role, actor_type, module, entity, record_id, action, before, after, reason)
  values (
    auth.uid(), coalesce(actor.display_name, actor.username, 'Quản trị viên'),
    case when actor.is_system_admin then 'system_admin' else 'staff' end, 'staff',
    'Expense', 'expenses', saved_expense.id::text, log_action,
    case when before_expense.id is null then null else to_jsonb(before_expense) end,
    to_jsonb(saved_expense) || jsonb_build_object('employee_name', employee_name),
    normalized_note
  );
  return jsonb_build_object('expense', to_jsonb(saved_expense), 'duplicateSalary', duplicate_salary);
end;
$$;
create or replace function public.archive_expense(p_id bigint, p_reason text default null)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  actor public.user_profiles%rowtype;
  before_expense public.expenses%rowtype;
  saved_expense public.expenses%rowtype;
  normalized_reason text := nullif(btrim(coalesce(p_reason, '')), '');
begin
  if not public.has_user_permission('expenses') then
    raise exception 'Không có quyền quản lý chi phí.' using errcode = '42501';
  end if;
  select * into actor from public.user_profiles where user_id = auth.uid();
  select * into before_expense from public.expenses where id = p_id and archived_at is null for update;
  if before_expense.id is null then raise exception 'Khoản chi không tồn tại hoặc đã hủy.'; end if;
  update public.expenses set archived_at = now(), archived_by = auth.uid()
  where id = p_id returning * into saved_expense;
  insert into public.audit_logs(actor_id, actor_name, actor_role, actor_type, module, entity, record_id, action, before, after, reason)
  values (
    auth.uid(), coalesce(actor.display_name, actor.username, 'Quản trị viên'),
    case when actor.is_system_admin then 'system_admin' else 'staff' end, 'staff',
    'Expense', 'expenses', saved_expense.id::text, 'archive_expense',
    to_jsonb(before_expense), to_jsonb(saved_expense), coalesce(normalized_reason, 'Hủy khoản chi')
  );
  return to_jsonb(saved_expense);
end;
$$;
create or replace function public.get_expense_report_summary(p_start_date date default null, p_end_date date default null)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
begin
  if not public.has_user_permission('reports') then
    raise exception 'Không có quyền xem báo cáo.' using errcode = '42501';
  end if;
  if p_start_date is not null and p_end_date is not null and p_start_date > p_end_date then
    raise exception 'Khoảng ngày báo cáo không hợp lệ.';
  end if;
  return jsonb_build_object(
    'totalExpense', coalesce((select sum(e.amount) from public.expenses e
      where e.archived_at is null
        and (p_start_date is null or e.expense_date >= p_start_date)
        and (p_end_date is null or e.expense_date <= p_end_date)), 0)
  );
end;
$$;
revoke all on function public.get_expenses_data(date,date,text,uuid,boolean) from public, anon;
revoke all on function public.check_duplicate_salary_expense(uuid,date,bigint) from public, anon;
revoke all on function public.save_expense(bigint,text,numeric,date,uuid,date,text,text) from public, anon;
revoke all on function public.archive_expense(bigint,text) from public, anon;
revoke all on function public.get_expense_report_summary(date,date) from public, anon;
grant execute on function public.get_expenses_data(date,date,text,uuid,boolean) to authenticated;
grant execute on function public.check_duplicate_salary_expense(uuid,date,bigint) to authenticated;
grant execute on function public.save_expense(bigint,text,numeric,date,uuid,date,text,text) to authenticated;
grant execute on function public.archive_expense(bigint,text) to authenticated;
grant execute on function public.get_expense_report_summary(date,date) to authenticated;
-- Make the four explicit expense actions visible in the default business-log mode.
create or replace function private.is_business_audit(action_value text, entity_value text,
  legacy_id bigint, reason_value text, before_value jsonb, after_value jsonb)
returns boolean language sql immutable set search_path='' as $$
  select legacy_id is null and coalesce(reason_value,'') <> 'Mirrored from legacy logs'
    and lower(coalesce(action_value,'')) = any(array[
      'create','update','delete','confirm','cancel','reject','approve','approved',
      'set_active','reset_password','update_profile','admin_reset_user_password',
      'admin_update_user_profile','admin_update_user_status','sync_permissions','lock_user','unlock_user',
      'adjust_wallet','admin_adjustment','admin_manual_renewal','confirm_payos','confirm_payos_batch',
      'admin_cancel','review_legacy_approve','review_legacy_cancel','create_promotion','update_promotion',
      'pause_promotion','reactivate_promotion','delete_promotion','expire','expired','activate','deactivate',
      'registration_pending','renewal_pending','renewal_paid','payment_review_required',
      'create_expense','create_salary_expense','update_expense','archive_expense'
    ])
    and not (lower(coalesce(action_value,''))='update'
      and (coalesce(before_value,'{}'::jsonb)-array['updated_at','total_paid','kiosk_total_paid','total_kiosks','last_payment_date'])
        is not distinct from (coalesce(after_value,'{}'::jsonb)-array['updated_at','total_paid','kiosk_total_paid','total_kiosks','last_payment_date']))
$$;
revoke all on function private.is_business_audit(text,text,bigint,text,jsonb,jsonb) from public;
commit;
