-- Employee V1. Forward-only; run locally before any separately authorized release.
-- Website identities remain separate. No payments/revenue/schema history is changed.
begin;
set local lock_timeout = '5s';
lock table public.expenses in share row exclusive mode;
create temporary table employee_v1_existing_contract on commit drop as select exists(select 1 from information_schema.columns where table_schema='public' and table_name='expenses' and column_name='employee_id') initialized;
create temporary table employee_v1_expense_before on commit drop as select id,to_jsonb(e) original from public.expenses e;

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  full_name text not null check(length(btrim(full_name)) between 1 and 160),
  phone text check(phone is null or length(phone)<=40),
  job_title text check(job_title is null or length(job_title)<=120),
  start_date date,
  employment_status text not null default 'active' check(employment_status in ('active','left')),
  notes text check(notes is null or length(notes)<=2000),
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table public.employees is 'Independent CRM people, not website accounts. Archive instead of delete.';
alter table public.employees enable row level security;
revoke all on public.employees from public,anon,authenticated;
grant select on public.employees to authenticated;
grant all on public.employees to service_role;
grant usage,select on sequence public.employees_id_seq to service_role;
drop policy if exists employees_expenses_read on public.employees;
create policy employees_expenses_read on public.employees for select to authenticated using((select public.has_user_permission('expenses')));
create index if not exists employees_status_name_idx on public.employees(employment_status,full_name,id) where archived_at is null;

-- Private provenance only: this is NOT an ongoing auth/user relationship.
create table if not exists private.employee_legacy_mapping (
  legacy_user_id uuid primary key,
  employee_id bigint not null unique references public.employees(id) on delete restrict,
  created_at timestamptz not null default now()
);
revoke all on private.employee_legacy_mapping from public,anon,authenticated;
alter table public.expenses add column if not exists employee_id bigint references public.employees(id) on delete restrict;
alter table public.expenses add column if not exists employee_name_snapshot text;
create index if not exists expenses_employee_id_idx on public.expenses(employee_id);
create index if not exists expenses_employee_salary_idx on public.expenses(employee_id,salary_period) where archived_at is null;
comment on column public.expenses.employee_user_id is 'Preserved legacy website-user attribution. New Expense UI uses employee_id.';
comment on column public.expenses.employee_name_snapshot is 'Name at attribution time; retained across Employee rename, leaving and archive.';

-- Do not rewrite original updated_at or any financial/business field during backfill.
alter table public.expenses disable trigger expenses_set_updated_at;
do $$
declare person record; new_id bigint;
begin
  if (select initialized from employee_v1_existing_contract) then return; end if;
  for person in
    select distinct up.user_id,btrim(up.display_name) full_name,up.phone
    from public.expenses e join public.user_profiles up on up.user_id=e.employee_user_id
    where e.employee_id is null and nullif(btrim(up.display_name),'') is not null
      and lower(btrim(up.display_name)) not in ('không tên','chưa có tên','người dùng đã xóa','unknown')
      and not exists(select 1 from private.employee_legacy_mapping m where m.legacy_user_id=up.user_id)
  loop
    -- A website status cannot prove current employment. Keep imported people archived
    -- until the Admin explicitly restores/confirms them. Same-name UUIDs are NOT merged.
    insert into public.employees(full_name,phone,archived_at,notes)
      values(person.full_name,person.phone,now(),'Chuyển từ liên kết chi phí cũ; cần xác nhận tình trạng làm việc.') returning id into new_id;
    insert into private.employee_legacy_mapping(legacy_user_id,employee_id) values(person.user_id,new_id);
  end loop;
end $$;
update public.expenses e set employee_id=m.employee_id
from private.employee_legacy_mapping m where e.employee_id is null and e.employee_user_id=m.legacy_user_id and not (select initialized from employee_v1_existing_contract);
-- Latest explicit save is authoritative; never search older names after an intentional clear.
with history as (
  select e.id,e.employee_user_id,e.employee_id,h.after,
    emp.full_name,up.display_name,up.username
  from public.expenses e left join public.employees emp on emp.id=e.employee_id
  left join public.user_profiles up on up.user_id=e.employee_user_id
  left join lateral(select al.after from public.audit_logs al
    where al.entity='expenses' and al.record_id=e.id::text
      and al.action in ('create_expense','create_salary_expense','update_expense')
    order by al.created_at desc,al.id desc limit 1) h on true
)
update public.expenses e set employee_name_snapshot=coalesce(
  case when nullif(h.after->>'employee_user_id','') is not null
      and (h.employee_user_id is null or h.after->>'employee_user_id'=h.employee_user_id::text)
    then nullif(btrim(h.after->>'employee_name'),'') end,
  h.full_name,nullif(btrim(h.display_name),''),nullif(btrim(h.username),''))
from history h where e.id=h.id and e.employee_name_snapshot is null and not (select initialized from employee_v1_existing_contract);
alter table public.expenses enable trigger expenses_set_updated_at;

alter table public.expenses drop constraint if exists expenses_salary_fields_check;
alter table public.expenses add constraint expenses_salary_fields_check check (
  (category='salary' and (employee_id is not null or employee_user_id is not null) and salary_period is not null and extract(day from salary_period)=1)
  or (category<>'salary' and salary_period is null)
);

create or replace function private.employee_lifecycle_guard() returns trigger language plpgsql set search_path='' as $$
begin
  if tg_op='DELETE' then raise exception 'Nhân viên chỉ được lưu trữ, không xóa.'; end if;
  new.updated_at:=now(); return new;
end $$;
revoke all on function private.employee_lifecycle_guard() from public,anon,authenticated;
drop trigger if exists employee_lifecycle_guard on public.employees;
create trigger employee_lifecycle_guard before update or delete on public.employees for each row execute function private.employee_lifecycle_guard();

create or replace function private.expense_employee_snapshot_guard() returns trigger language plpgsql set search_path='' as $$
declare person public.employees%rowtype;
begin
  if tg_op='UPDATE' and new.employee_id is not distinct from old.employee_id then
    new.employee_name_snapshot:=old.employee_name_snapshot;
    return new;
  end if;
  if new.employee_id is null then new.employee_name_snapshot:=null; return new; end if;
  select * into person from public.employees where id=new.employee_id for share;
  if person.id is null or person.archived_at is not null or person.employment_status<>'active' then
    raise exception 'Chỉ chọn nhân viên đang làm và chưa lưu trữ cho liên kết mới.';
  end if;
  new.employee_name_snapshot:=person.full_name;
  return new;
end $$;
revoke all on function private.expense_employee_snapshot_guard() from public,anon,authenticated;
drop trigger if exists expense_employee_snapshot_guard on public.expenses;
create trigger expense_employee_snapshot_guard before insert or update on public.expenses for each row execute function private.expense_employee_snapshot_guard();

create or replace function private.log_employee_change(previous public.employees,saved public.employees,message text)
returns void language plpgsql set search_path='' as $$
begin
  insert into public.audit_logs(actor_id,actor_name,actor_role,actor_type,module,entity,record_id,action,before,after,reason)
  select auth.uid(),coalesce(up.display_name,up.username,'Quản trị viên'),case when up.is_system_admin then 'system_admin' else 'staff' end,'staff',
    'Employee','employees',saved.id::text,case when previous.id is null then 'create' else 'update' end,
    case when previous.id is null then null else to_jsonb(previous) end,to_jsonb(saved),message
  from public.user_profiles up where up.user_id=auth.uid();
end $$;
revoke all on function private.log_employee_change(public.employees,public.employees,text) from public,anon,authenticated;

create or replace function public.get_employees_data(p_search text default null,p_status text default null,p_include_archived boolean default false)
returns jsonb language plpgsql stable security definer set search_path='' as $$
begin
  if not public.has_user_permission('expenses') then raise exception 'Không có quyền quản lý nhân viên.' using errcode='42501'; end if;
  return jsonb_build_object('rows',coalesce((select jsonb_agg(to_jsonb(e) order by e.archived_at nulls first,e.full_name,e.id)
    from public.employees e where (p_include_archived or e.archived_at is null)
    and (nullif(p_status,'') is null or e.employment_status=p_status)
    and (nullif(btrim(p_search),'') is null or concat_ws(' ',e.full_name,e.phone,e.job_title) ilike '%'||btrim(p_search)||'%')),'[]'::jsonb));
end $$;
create or replace function public.save_employee(p_id bigint,p_full_name text,p_phone text default null,p_job_title text default null,p_start_date date default null,p_employment_status text default 'active',p_notes text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare previous public.employees%rowtype; saved public.employees%rowtype; message text;
begin
  if not public.has_user_permission('expenses') then raise exception 'Không có quyền quản lý nhân viên.' using errcode='42501'; end if;
  if p_full_name is null or length(btrim(p_full_name)) not between 1 and 160 then raise exception 'Họ tên phải có từ 1 đến 160 ký tự.'; end if;
  if p_employment_status is null or p_employment_status not in ('active','left') then raise exception 'Trạng thái làm việc không hợp lệ.'; end if;
  if p_id is null then
    insert into public.employees(full_name,phone,job_title,start_date,employment_status,notes)
    values(btrim(p_full_name),nullif(btrim(p_phone),''),nullif(btrim(p_job_title),''),p_start_date,p_employment_status,nullif(btrim(p_notes),'')) returning * into saved;
    message:='Đã tạo nhân viên '||saved.full_name;
  else
    select * into previous from public.employees where id=p_id for update;
    if previous.id is null then raise exception 'Nhân viên không tồn tại.'; end if;
    if previous.archived_at is not null then raise exception 'Khôi phục nhân viên trước khi chỉnh sửa.'; end if;
    update public.employees set full_name=btrim(p_full_name),phone=nullif(btrim(p_phone),''),job_title=nullif(btrim(p_job_title),''),
      start_date=p_start_date,employment_status=p_employment_status,notes=nullif(btrim(p_notes),'') where id=p_id returning * into saved;
    message:=case when previous.employment_status<>saved.employment_status then saved.full_name||case when saved.employment_status='left' then ' đã nghỉ việc' else ' đã làm việc trở lại' end else 'Đã cập nhật nhân viên '||saved.full_name end;
  end if;
  perform private.log_employee_change(previous,saved,message);
  return to_jsonb(saved);
end $$;
create or replace function public.set_employee_lifecycle(p_id bigint,p_action text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare previous public.employees%rowtype; saved public.employees%rowtype; message text;
begin
  if not public.has_user_permission('expenses') then raise exception 'Không có quyền quản lý nhân viên.' using errcode='42501'; end if;
  select * into previous from public.employees where id=p_id for update;
  if previous.id is null then raise exception 'Nhân viên không tồn tại.'; end if;
  if p_action is null or p_action not in ('archive','restore','left','reactivate') then raise exception 'Thao tác không hợp lệ.'; end if;
  if previous.archived_at is not null and p_action not in ('restore','archive') then raise exception 'Khôi phục nhân viên trước khi đổi trạng thái.'; end if;
  if (p_action='archive' and previous.archived_at is not null) or (p_action='restore' and previous.archived_at is null)
    or (p_action='left' and previous.employment_status='left') or (p_action='reactivate' and previous.employment_status='active') then return to_jsonb(previous); end if;
  update public.employees set archived_at=case when p_action='archive' then now() when p_action='restore' then null else archived_at end,
    employment_status=case when p_action='left' then 'left' when p_action='reactivate' then 'active' else employment_status end
    where id=p_id returning * into saved;
  message:=case p_action when 'archive' then 'Đã lưu trữ nhân viên '||saved.full_name when 'restore' then 'Đã khôi phục nhân viên '||saved.full_name
    when 'left' then saved.full_name||' đã nghỉ việc' else saved.full_name||' đã làm việc trở lại' end;
  perform private.log_employee_change(previous,saved,message);
  return to_jsonb(saved);
end $$;

create or replace function public.get_employee_expenses_data(p_start_date date default null,p_end_date date default null,p_category text default null,p_employee_id bigint default null,p_include_archived boolean default false)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare result jsonb; total_revenue numeric;
begin
  if not public.has_user_permission('expenses') then raise exception 'Không có quyền quản lý chi phí.' using errcode='42501'; end if;
  if p_start_date is not null and p_end_date is not null and p_start_date>p_end_date then raise exception 'Khoảng ngày chi phí không hợp lệ.'; end if;
  if p_category is not null and not exists(select 1 from public.expense_categories where code=p_category) then raise exception 'Danh mục chi phí không hợp lệ.'; end if;
  select coalesce(sum(p.total_amount),0) into total_revenue from public.payment_business_dates p
    where lower(p.payment_status)='completed' and p.confirmed_at is not null
      and (p_start_date is null or p.revenue_date>=p_start_date) and (p_end_date is null or p.revenue_date<=p_end_date);
  with filtered as materialized (
    select e.*,c.name category_name,c.is_salary category_is_salary,
      coalesce(e.employee_name_snapshot,emp.full_name,nullif(btrim(up.display_name),''),up.username,
        case when e.employee_user_id is not null then 'Chưa liên kết nhân viên' else 'Không gắn nhân viên' end) employee_name,
      emp.full_name employee_current_name,emp.employment_status,emp.archived_at employee_archived_at,
      case when e.employee_id is not null then 'linked' when e.employee_user_id is not null or e.employee_name_snapshot is not null then 'legacy' else 'unassigned' end attribution_state,
      coalesce(creator.display_name,creator.username,'Quản trị viên') creator_name
    from public.expenses e join public.expense_categories c on c.id=e.category_id
    left join public.employees emp on emp.id=e.employee_id left join public.user_profiles up on up.user_id=e.employee_user_id
    left join public.user_profiles creator on creator.user_id=e.created_by
    where (p_include_archived or e.archived_at is null)
      and (p_start_date is null or e.expense_date>=p_start_date) and (p_end_date is null or e.expense_date<=p_end_date)
      and (p_category is null or c.code=p_category) and (p_employee_id is null or e.employee_id=p_employee_id)
  ) select jsonb_build_object('rows',coalesce((select jsonb_agg(to_jsonb(f) order by f.expense_date desc,f.id desc) from filtered f),'[]'::jsonb),
    'totalAmount',coalesce((select sum(amount) from filtered),0),'totalExpense',coalesce((select sum(amount) from filtered),0),
    'totalRevenue',total_revenue,'netProfit',total_revenue-coalesce((select sum(amount) from filtered),0),'totalRows',(select count(*) from filtered),
    'categories',coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'code',c.code,'name',c.name,'isSalary',c.is_salary,'isActive',c.is_active) order by c.is_active desc,c.name) from public.expense_categories c),'[]'::jsonb),
    'employees',coalesce((select jsonb_agg(to_jsonb(emp) order by emp.full_name,emp.id) from public.employees emp),'[]'::jsonb)) into result;
  return result;
end $$;

create or replace function public.check_employee_salary_duplicate(p_employee_id bigint,p_salary_period date,p_exclude_id bigint default null)
returns boolean language plpgsql stable security definer set search_path='' as $$
begin
  if not public.has_user_permission('expenses') then raise exception 'Không có quyền quản lý chi phí.' using errcode='42501'; end if;
  return exists(select 1 from public.expenses e join public.expense_categories c on c.id=e.category_id
    where c.is_salary and e.employee_id=p_employee_id and e.salary_period=date_trunc('month',p_salary_period)::date
      and e.archived_at is null and (p_exclude_id is null or e.id<>p_exclude_id));
end $$;

create or replace function public.save_employee_expense(p_id bigint,p_category text,p_amount numeric,p_expense_date date,p_employee_id bigint,p_salary_period date,p_payment_method text,p_note text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare actor public.user_profiles%rowtype; previous public.expenses%rowtype; saved public.expenses%rowtype;
  category_row public.expense_categories%rowtype; normalized_category text:=lower(btrim(coalesce(p_category,'')));
  normalized_method text:=lower(btrim(coalesce(p_payment_method,''))); normalized_note text:=nullif(btrim(coalesce(p_note,'')),'');
  normalized_period date:=case when p_salary_period is null then null else date_trunc('month',p_salary_period)::date end;
  duplicate_salary boolean:=false; log_action text;
begin
  if not public.has_user_permission('expenses') then raise exception 'Không có quyền quản lý chi phí.' using errcode='42501'; end if;
  if p_id is not null then
    select * into previous from public.expenses where id=p_id and archived_at is null for update;
    if previous.id is null then raise exception 'Khoản chi không tồn tại hoặc đã hủy.'; end if;
  end if;
  select * into category_row from public.expense_categories where code=normalized_category and (is_active or id=previous.category_id);
  if category_row.id is null then raise exception 'Danh mục chi phí không hợp lệ hoặc đã lưu trữ.'; end if;
  if p_amount is null or p_amount<=0 or p_amount::text in ('NaN','Infinity','-Infinity') then raise exception 'Số tiền phải lớn hơn 0.'; end if;
  if p_expense_date is null then raise exception 'Ngày chi là bắt buộc.'; end if;
  if normalized_method='' or length(normalized_method)>50 then raise exception 'Phương thức chi không hợp lệ.'; end if;
  if category_row.is_salary and (normalized_period is null or (p_employee_id is null and not (previous.id is not null and previous.employee_id is null and previous.employee_user_id is not null))) then
    raise exception 'Lương cần có nhân viên và kỳ lương.';
  end if;
  if not category_row.is_salary then normalized_period:=null; end if;
  select * into actor from public.user_profiles where user_id=auth.uid();
  if actor.user_id is null then raise exception 'Không tìm thấy tài khoản thực hiện.' using errcode='42501'; end if;
  duplicate_salary:=category_row.is_salary and public.check_employee_salary_duplicate(p_employee_id,normalized_period,p_id);
  if p_id is null then
    insert into public.expenses(category,category_id,amount,expense_date,employee_id,salary_period,payment_method,note,created_by)
    values(category_row.code,category_row.id,p_amount,p_expense_date,p_employee_id,normalized_period,normalized_method,normalized_note,auth.uid()) returning * into saved;
    log_action:=case when category_row.is_salary then 'create_salary_expense' else 'create_expense' end;
  else
    update public.expenses set category=category_row.code,category_id=category_row.id,amount=p_amount,expense_date=p_expense_date,
      employee_id=p_employee_id,salary_period=normalized_period,payment_method=normalized_method,note=normalized_note
      where id=p_id returning * into saved;
    log_action:='update_expense';
  end if;
  insert into public.audit_logs(actor_id,actor_name,actor_role,actor_type,module,entity,record_id,action,before,after,reason)
  values(auth.uid(),coalesce(actor.display_name,actor.username,'Quản trị viên'),case when actor.is_system_admin then 'system_admin' else 'staff' end,'staff',
    'Expense','expenses',saved.id::text,log_action,case when previous.id is null then null else to_jsonb(previous) end,
    to_jsonb(saved)||jsonb_build_object('employee_name',saved.employee_name_snapshot,'category_name',category_row.name),
    case when category_row.is_salary then 'Ghi nhận lương '||to_char(normalized_period,'MM/YYYY')||' cho '||coalesce(saved.employee_name_snapshot,'nhân viên')||' – '||trim(to_char(p_amount,'FM999G999G999G990'))||'đ'
      when log_action='update_expense' then 'Sửa chi phí '||trim(to_char(p_amount,'FM999G999G999G990'))||'đ – '||category_row.name
      else 'Thêm chi phí '||trim(to_char(p_amount,'FM999G999G999G990'))||'đ – '||category_row.name end);
  return jsonb_build_object('expense',to_jsonb(saved),'duplicateSalary',duplicate_salary);
end $$;
-- Retire the old account-based mutation. Old clients must reload the new UI.
revoke all on function public.save_expense(bigint,text,numeric,date,uuid,date,text,text) from public,anon,authenticated;

revoke all on function public.get_employees_data(text,text,boolean) from public,anon;
revoke all on function public.save_employee(bigint,text,text,text,date,text,text) from public,anon;
revoke all on function public.set_employee_lifecycle(bigint,text) from public,anon;
revoke all on function public.get_employee_expenses_data(date,date,text,bigint,boolean) from public,anon;
revoke all on function public.check_employee_salary_duplicate(bigint,date,bigint) from public,anon;
revoke all on function public.save_employee_expense(bigint,text,numeric,date,bigint,date,text,text) from public,anon;
grant execute on function public.get_employees_data(text,text,boolean) to authenticated;
grant execute on function public.save_employee(bigint,text,text,text,date,text,text) to authenticated;
grant execute on function public.set_employee_lifecycle(bigint,text) to authenticated;
grant execute on function public.get_employee_expenses_data(date,date,text,bigint,boolean) to authenticated;
grant execute on function public.check_employee_salary_duplicate(bigint,date,bigint) to authenticated;
grant execute on function public.save_employee_expense(bigint,text,numeric,date,bigint,date,text,text) to authenticated;

-- The rest of this migration extends the existing journal only for Logs context.


create or replace function public.get_business_events(
  p_context text default 'logs',p_search_term text default null,p_actor_filter text default null,
  p_activity_filter text default null,p_source_filter text default null,
  p_from_time timestamptz default null,p_to_time timestamptz default null,
  p_page integer default 1,p_page_size integer default 20
) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare result jsonb; normalized_page integer:=greatest(coalesce(p_page,1),1);
  normalized_size integer:=case when p_page_size in(5,10,20,50) then p_page_size else 20 end;
begin
  if lower(coalesce(p_context,''))='dashboard' then
    if not public.has_user_permission('dashboard') then raise exception 'Không có quyền xem Dashboard.' using errcode='42501'; end if;
  elsif not public.has_user_permission('logs') then raise exception 'Không có quyền xem Business Logs.' using errcode='42501'; end if;
  with payment_events as materialized (
    select 'payment:'||p.id event_key,
      case when exists(select 1 from public.registration_requests r where r.payment_id=p.id and lower(coalesce(r.metadata->>'request_type',r.metadata->>'source',r.metadata->>'registration_type','')) similar to '%(legacy|additional)%') then 'legacy'
        when p.registration_batch_id is not null or p.registration_request_id is not null then 'registration'
        when lower(coalesce(p.transaction_type,''))='renewal' or lower(coalesce(p.payment_intent_key,'')) like '%renewal:%' then 'renewal' else 'reconciliation' end event_type,
      case when exists(select 1 from public.registration_requests r where r.payment_id=p.id and lower(coalesce(r.metadata->>'request_type',r.metadata->>'source',r.metadata->>'registration_type','')) similar to '%(legacy|additional)%') then 'Bổ sung / Legacy'
        when p.registration_batch_id is not null or p.registration_request_id is not null then 'Đăng ký Kiosk'
        when lower(coalesce(p.transaction_type,''))='renewal' then 'Gia hạn' else 'Đối soát' end activity_label,
      coalesce(k.facebook_name,c.facebook_name,'Kiosk') subject_name,p.total_amount amount,p.confirmed_at occurred_at,
      case when p.confirmed_by is null or lower(p.payment_method)='payos' then 'PayOS' else 'Admin' end source,
      coalesce(p.confirmed_by,'PayOS') actor_name,
      case when exists(select 1 from public.registration_requests r where r.payment_id=p.id and lower(coalesce(r.metadata->>'request_type',r.metadata->>'source',r.metadata->>'registration_type','')) similar to '%(legacy|additional)%') then 'Bổ sung Kiosk '||coalesce(k.facebook_name,c.facebook_name,'')||' thành công'
        when p.registration_batch_id is not null or p.registration_request_id is not null then 'Đăng ký Kiosk '||coalesce(k.facebook_name,c.facebook_name,'')||' thành công'
        when lower(coalesce(p.transaction_type,''))='renewal' then 'Kiosk '||coalesce(k.facebook_name,'')||' đã gia hạn '||coalesce(p.months,0)||' tháng'
        else 'Thanh toán #'||p.id||' cần đối soát intent' end title,
      trim(to_char(p.total_amount,'FM999G999G999G990'))||' VNĐ · '||coalesce(nullif(p.payment_method,''),'PayOS') secondary,'Hoàn tất' result
    from public.payment_business_dates p left join public.kiosks k on k.id=p.kiosk_id left join public.customers c on c.id=p.customer_id
    where p.payment_status='completed' and p.confirmed_at is not null
  ), legacy_events as materialized (
    select 'request:'||r.id event_key,'legacy' event_type,'Bổ sung / Legacy' activity_label,
      coalesce(k.facebook_name,r.facebook_name,'Kiosk') subject_name,coalesce(r.total_amount,0) amount,r.reviewed_at occurred_at,
      'Admin' source,coalesce(up.display_name,up.username,'Admin') actor_name,
      'Bổ sung Kiosk '||coalesce(k.facebook_name,r.facebook_name,'')||' thành công' title,
      case when coalesce(r.total_amount,0)>0 then trim(to_char(r.total_amount,'FM999G999G999G990'))||' VNĐ' else null end secondary,'Hoàn tất' result
    from public.registration_requests r left join public.kiosks k on k.id=r.kiosk_id left join public.user_profiles up on up.user_id=r.reviewed_by
    where r.status='approved' and r.reviewed_at is not null and r.payment_id is null
      and lower(coalesce(r.metadata->>'request_type',r.metadata->>'source',r.metadata->>'registration_type','')) similar to '%(legacy|additional)%'
  ), reconciliation_events as materialized (
    select 'reconciliation:'||o.id event_key,'reconciliation' event_type,'Đối soát' activity_label,
      coalesce(k.facebook_name,c.facebook_name,'Thanh toán') subject_name,o.amount,o.updated_at occurred_at,'PayOS' source,'PayOS' actor_name,
      'Giao dịch PayOS cần Admin đối soát' title,coalesce(o.reconciliation_reason,'Không xác định được intent') secondary,'Cần xử lý' result
    from public.payos_orders o left join public.payments p on p.id=o.payment_id left join public.kiosks k on k.id=p.kiosk_id left join public.customers c on c.id=p.customer_id
    where o.reconciliation_required
  ), audit_events as materialized (
    select 'audit:'||al.id event_key,
      case when lower(coalesce(al.module,''))='employee' then 'employee'
        when lower(coalesce(al.module,''))='payment' and al.after->>'correction_type'='historical_payment' then 'payment'
        when lower(coalesce(al.module,'')) in('expense','expenses') then 'expense'
        when lower(coalesce(al.module,'')) in('homepage','homepage content','website','featured business') then 'website'
        when lower(coalesce(al.action,'')) similar to '%(cancel|reject|delete|archive)%' then 'cancel'
        when lower(coalesce(al.entity,'')) like '%kiosk%' and lower(coalesce(al.action,'')) similar to '%(status|suspend|reactivat|deactivat)%' then 'status' else 'update' end event_type,
      case when lower(coalesce(al.module,''))='employee' then 'Nhân viên'
        when lower(coalesce(al.module,''))='payment' then 'Điều chỉnh thanh toán'
        when lower(coalesce(al.module,'')) in('expense','expenses') then 'Chi phí'
        when lower(coalesce(al.module,'')) in('homepage','homepage content','website','featured business') then 'Nội dung Website'
        when lower(coalesce(al.action,'')) similar to '%(cancel|reject|delete|archive)%' then 'Hủy'
        when lower(coalesce(al.entity,'')) like '%kiosk%' and lower(coalesce(al.action,'')) similar to '%(status|suspend|reactivat|deactivat)%' then 'Trạng thái Kiosk' else 'Cập nhật' end activity_label,
      coalesce(case when lower(coalesce(al.module,''))='employee' then nullif(al.after->>'full_name','') end,nullif(al.after->>'facebook_name',''),nullif(al.after->>'name',''),nullif(al.before->>'facebook_name',''),nullif(al.before->>'name',''),al.entity,'Bản ghi') subject_name,
      case when lower(coalesce(al.module,''))='payment' and al.after->>'correction_type'='historical_payment' then nullif(al.after->>'total_amount','')::numeric else null::numeric end amount,
      al.created_at occurred_at,'CRM' source,coalesce(nullif(al.actor_name,''),'Hệ thống') actor_name,
      case
        when lower(coalesce(al.module,''))='employee' then al.reason
        when lower(coalesce(al.module,''))='payment' then coalesce(nullif(al.actor_name,''),'Admin')||' đã cập nhật thanh toán lịch sử #'||coalesce(al.record_id,al.after->>'payment_id','')
        when lower(coalesce(al.module,'')) in('expense','expenses') then coalesce(nullif(al.actor_name,''),'Admin')||' · '||coalesce(nullif(al.reason,''),'Cập nhật chi phí')
        when lower(coalesce(al.module,'')) in('homepage','homepage content','website','featured business') then coalesce(nullif(al.actor_name,''),'Admin')||' đã cập nhật nội dung Website'
        when lower(coalesce(al.entity,'')) like '%customer%' then coalesce(nullif(al.actor_name,''),'Admin')||case when lower(al.action)='create' then ' đã thêm khách hàng ' else ' đã cập nhật khách hàng ' end||coalesce(nullif(al.after->>'facebook_name',''),nullif(al.before->>'facebook_name',''),'')
        when lower(coalesce(al.entity,'')) like '%kiosk%' then coalesce(nullif(al.actor_name,''),'Admin')||case when lower(al.action)='create' then ' đã thêm Kiosk ' else ' đã cập nhật Kiosk ' end||coalesce(nullif(al.after->>'facebook_name',''),nullif(al.before->>'facebook_name',''),'')
        else coalesce(nullif(al.actor_name,''),'Admin')||' · '||coalesce(nullif(al.reason,''),'Cập nhật nghiệp vụ') end title,
      case when nullif(al.reason,'') is not null and lower(coalesce(al.module,'')) not in('expense','expenses','employee') then al.reason else null end secondary,'Hoàn tất' result
    from public.audit_logs al
    where private.is_business_audit(al.action,al.entity,al.legacy_log_id,al.reason,al.before,al.after)
      and ((lower(coalesce(p_context,''))='logs' and lower(coalesce(al.module,''))='employee')
        or (lower(coalesce(al.module,''))='payment' and al.after->>'correction_type'='historical_payment')
        or lower(coalesce(al.module,'')) in('expense','expenses','homepage','homepage content','website','featured business','customer','customers','kiosk','kiosks')
        or (lower(coalesce(al.module,'')) in('registration','registrations') and lower(coalesce(al.action,'')) similar to '%(cancel|reject|delete|archive)%'))
  ), all_events as (
    select * from payment_events union all select * from legacy_events union all select * from reconciliation_events union all select * from audit_events
  ), filtered as materialized (
    select * from all_events e where (p_from_time is null or e.occurred_at>=p_from_time) and (p_to_time is null or e.occurred_at<p_to_time)
      and (nullif(btrim(p_activity_filter),'') is null or e.event_type=lower(p_activity_filter))
      and (nullif(btrim(p_source_filter),'') is null or lower(e.source)=lower(p_source_filter))
      and (nullif(btrim(p_actor_filter),'') is null or e.actor_name ilike '%'||btrim(p_actor_filter)||'%')
      and (nullif(btrim(p_search_term),'') is null or concat_ws(' ',e.title,e.secondary,e.subject_name,e.activity_label) ilike '%'||btrim(p_search_term)||'%')
  ), paged as(select * from filtered order by occurred_at desc,event_key desc limit normalized_size offset(normalized_page-1)*normalized_size)
  select jsonb_build_object('rows',coalesce((select jsonb_agg(to_jsonb(p) order by occurred_at desc,event_key desc) from paged p),'[]'::jsonb),
    'total',(select count(*) from filtered),'page',normalized_page,'pageSize',normalized_size) into result;
  return result;
end;
$$;

revoke all on function public.get_business_events(text,text,text,text,text,timestamptz,timestamptz,integer,integer) from public,anon;
grant execute on function public.get_business_events(text,text,text,text,text,timestamptz,timestamptz,integer,integer) to authenticated;


-- Abort atomically if even one original field/row changed, including timestamps.
do $$
begin
  if exists(select 1 from employee_v1_expense_before b full join public.expenses e using(id)
    where b.id is null or e.id is null or
      (b.original-array['employee_id','employee_name_snapshot']) is distinct from (to_jsonb(e)-array['employee_id','employee_name_snapshot'])) then
    raise exception 'Employee migration changed historical Expense data; rolling back.';
  end if;
end $$;
commit;
